### ISSUE TITLE
Command line flags do not work after code formatter/beautifier

### ISSUE THREAD

**Issue by vladimirgamalyan** [onqtam/doctest#104]
## Description

Visual studio 2017 automatically formats code when I paste code from github.com/doctest.h. Everything works fine, but a few command line flags.
I guess, additional spaces in calls DOCTEST_PARSE_AS_BOOL_OR_FLAG do the bug.

### Steps to reproduce

Add spaces (around '-') to:
`DOCTEST_PARSE_AS_BOOL_OR_FLAG(dt - exit, dt - e, exit, false);`

Now, `shouldExit()` always returns false (with "--exit" arg).

### Extra information

* doctest version: **v1.2.6**
* Operating System: **Windows 10 x64 build 1709**
* Compiler+version: **Visual Studio 2017**

**Comment by onqtam** [comment]
For that particular piece of code I've turned off clang-format (using ```// clang-format off``` and ```// clang-format on```). This isn't a doctest issue per-se.

Well I'm not sure what to do about this... Can you download the file and just open/use it instead of pasting its contents in VS?

**Comment by vladimirgamalyan** [comment]
Sure, I'v already downloaded the file (and exclude it from pre-git-hook style tools).
I think this format-depended code a bit fragile, so it would be nice if a compilation error occurred in case you accidentally reformat sources.

**Comment by onqtam** [comment]
I'll think about how to avoid this, thanks :)

**Comment by vladimirgamalyan** [comment]
BTW is there some penalty (compile time) with quoted strings as macros arguments?

**Comment by onqtam** [comment]
If you are wondering if I can pass something like ```"dt-success"``` to ```DOCTEST_PARSE_AS_BOOL_OR_FLAG``` and just concatenate in the macro the given string with ```"="``` in [here](https://github.com/onqtam/doctest/blob/1.2.6/doctest/doctest.h#L5327) - I'm wondering the same - and will try it :)
