### ISSUE TITLE
Nullptr issue.

### ISSUE THREAD

**Issue by iSLC** [onqtam/doctest#110]
## Description
I was trying to test a string view default constructor and to see if the pointer was indeed null. Since I've assigned `nullptr` to it.

### Steps to reproduce
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

struct test
{
	const char * ptr;

	test() : ptr(nullptr) { }

	const char * get() const { return ptr; }
};

TEST_CASE("dummy")
{
    test o;
    FAST_REQUIRE_NE(o.get(), nullptr);
}
```

Output:
```
src\main.cpp(15)
TEST CASE:  dummy

src\main.cpp(19) FATAL ERROR!
  FAST_REQUIRE_NE( o.get(), nullptr )
with expansion:
  FAST_REQUIRE_NE( NULL, nullptr )
```

Am I required to use `NULL` instead of `nullptr` ? Because I would prefer the later.

### Extra information
* doctest version: **v1.2.6**
* Operating System: **Windows**
* Compiler+version: **gcc version 7.2.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)**

**Comment by iSLC** [comment]
Seems to work if i use `CHECK(o.get() == nullptr);` I guess I should use that instead. But still bothers me why the first approach failed.

**Comment by iSLC** [comment]
Never mind. I was too focused on the error to notice my copy/paste mistake. As I was testing `NE` instead of `EQ`. My apologies.

**Comment by onqtam** [comment]
Glad you solved the issue :)
