### ISSUE TITLE
clang-tidy warning about cert-err58-cpp

### ISSUE THREAD

**Issue by alpha-X-omega** [onqtam/doctest#115]
## Description
run-clang-tidy-5.0.py is detecting

   warning: initialization of '_DOCTEST_ANON_VAR_3' with static storage duration may throw an 
   exception that cannot be caught [cert-err58-cpp] TEST_CASE("example") {

The macro expansion ended at

   note: possibly throwing constructor declared here
        TestCase(funcType test, const char* file, unsigned line, const TestSuite& test_suite,

### Extra information
* doctest version: **v42.42.42**
* Operating System: **Ubuntu 16.04.3**
* Compiler+version: **Clang-5.0**

The good news is that doctest satisfies all the other checks :)

**Comment by onqtam** [comment]
Any idea how to suppress this? I cannot use ```// NOLINT``` where the macros are defined because that has to be used where they are used. I also don't want to add a ```try {} catch(...) {}``` block in the test registration function just because of this...

**Comment by alpha-X-omega** [comment]
I passed `--line-filter=[{"name":` "<absolute_path>/doctest/doctest.h", "lines": [[1, 3048], [3050, 5701]]}]` to clang-tidy :-)

**Comment by onqtam** [comment]
In that case I'll be happy to close this issue :D

**Comment by BrannonKing** [comment]
This is clearly not fixed. CLion complains about it on every test.

**Comment by onqtam** [comment]
@BrannonKing Can you use the workaround that is provided in the issue (with using ```--line-filter=...```)?

I might think about adding ```noexcept``` but this is not a priority for now - let me know if you want this issue reopened and something done about it..........

**Comment by onqtam** [comment]
It seems that this is actually solvable precisely by using ```// NOLINT``` - as can be seen in this PR:

https://github.com/onqtam/doctest/pull/159

**Comment by Trass3r** [comment]
> I might think about adding `noexcept` but this is not a priority for now - let me know if you want this issue reopened and something done about it.

I'd also expect these kind of diagnostics to be resolvable by `noexcept`/`constexpr`.

**Comment by onqtam** [comment]
Back in 2018 `noexcept` wasn't being used in doctest (I think). Now it is.

So yes, we should prefer using `DOCTEST_NOEXCEPT` to suppressing linter warnings. PRs are welcome!

**Comment by serguei-k** [comment]
Hi Viktor,
making the following change suppresses this warning:
`static const int var = doctest::detail::consume(&var, __VA_ARGS__); // NOLINT(cert-err58-cpp)  \`

Do you mind if I make a PR for this?

**Comment by onqtam** [comment]
sure!
