### ISSUE TITLE
MSan has runtime error: unsigned integer overflow

### ISSUE THREAD

**Issue by alpha-X-omega** [onqtam/doctest#116]
I just turned on Clang's Memory Sanitizer and it complained about this.  The existing test cases in the tutorial will suffice to reproduce this issue.

/usr/include/c++/v1/__tree:836:16: runtime error: downcast of address 0x000002ce73c0 with insufficient space for an object of type 'std::__1::__tree_node<doctest::detail::TestCase, void *>'
0x000002ce73c0: note: pointer points here
 80 70 00 00  00 00 00 00 80 70 00 00  02 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00  00 00 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/include/c++/v1/__tree:836:16 in 
doctest/doctest.h:4146:45: runtime error: unsigned integer overflow: 9 - 87 cannot be represented in type 'unsigned int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior doctest/doctest.h:4146:45 in 
==44126==WARNING: MemorySanitizer: use-of-uninitialized-value

**Comment by onqtam** [comment]
Hi!

There have been previous similar reports - is your standard library also instrumented for msan? This seems like it's in the implementation of ```std::set<>```

**Comment by alpha-X-omega** [comment]
Hi!

You're a genius!  How silly of me to think anything works out of the box :-)

Thank you.
