### ISSUE TITLE
Terminal color is not reset when a test fails with some signal

### ISSUE THREAD

**Issue by obfuscated** [onqtam/doctest#122]
This simple test code:

`TEST_CASE("failure")
{
    int *a=nullptr;
    *a=5;
}`

can be used to reproduce the problem.

I'm testing on OS X at the moment. Don't know if this reproduces on Linux/Windows...

**Comment by onqtam** [comment]
Couldn't reproduce on Windows, but I checked the logic aaand:
- if there is a signal and it is caught - the ```printSummary()``` function is called and it resets the terminal color at its end properly.
- if the signal is not caught then the framework cannot do anything anyway

**Comment by onqtam** [comment]
By "not caught" I mean environments such as virtual machines where I've been unable to catch signals from crashes. But I'll reopen this issue to test it at some point in time.

**Comment by patryk-oleniuk** [comment]
I was able to reproduce this issue on Linux (Ubuntu 14.04) 


![image](https://user-images.githubusercontent.com/32352418/43286014-97979b9e-90d5-11e8-92fb-f5124ca61e4e.png)

**Comment by piluke** [comment]
This is also happening for me when I kill it with Ctrl-C. I'm using doctest version 2.0.1.

**Comment by DenisYaroshevskiy** [comment]
Hi

Just wanted to +1. Mac.

**Comment by onqtam** [comment]
I just pushed a change - let me know if it works for you!

**Comment by DenisYaroshevskiy** [comment]
@onqtam - didn't help.
Did you update the single header?

**Comment by onqtam** [comment]
@DenisYaroshevskiy I did - but in the ```dev``` branch - it's not yet in ```master```. I also managed to reproduce the issue on my local linux and this commit managed to fix it: https://github.com/onqtam/doctest/commit/2d36c236563cb39e64a76255372cc391deba0d51

Can you confirm that you indeed tried the ```dev``` branch? If so, I'll think about it more perhaps tomorrow.

**Comment by DenisYaroshevskiy** [comment]
@onqtam - I used the link from the docs, so I doubt it. Can you give me a link to a new file?

**Comment by onqtam** [comment]
@DenisYaroshevskiy https://github.com/onqtam/doctest/blob/dev/doctest/doctest.h (the ```dev``` part from the URL can be substituted for ```master``` or a specific version tag like ```2.2.0```)

**Comment by DenisYaroshevskiy** [comment]
@onqtam - yes, now it fixed, thanks.

Thanks for letting me know about your test library - I'd use it from now on for my projects since it compiles so fast even with main in regular tests!
