### ISSUE TITLE
scan-build report "Dereference of null pointer" for function wildcmp

### ISSUE THREAD

**Issue by cyyever** [onqtam/doctest#124]
The detail analysis is in my uploaded screenshot image. I think this is not a false positive,please   check it .
![screenshot from 2018-04-12 14-52-43](https://user-images.githubusercontent.com/17618148/38660916-95387786-3e61-11e8-8a8d-7cdc20d8e547.png)

**Comment by onqtam** [comment]
Well that function is basically taken from [here](https://www.codeproject.com/Articles/1088/Wildcard-string-compare-globbing) - its been around for almost 20 years and I don't see reports of crashes/null derefs.

I also tried to come up with a scenario where it would fail but couldn't - traced the logic a bunch of times.

I think what the analyzer thinks is that we can get to ```str  = cp++;``` without ever having gotten to initializing it (```cp = str + 1;```) but I don't think that is possible.

So I'm closing this as a false positive - until someone comes up with a test case where this crashes.
