### ISSUE TITLE
Support Intel Compiler

### ISSUE THREAD

**Issue by smcallis** [onqtam/doctest#128]
It'd be great if doctest could compile under Intel >= 13.  It has _most_ of C++11, but a few things missing, notable thread_local.   I'd be happy to submit a pull request if someone could give me a rundown on what needs to be detected and configured.

**Comment by onqtam** [comment]
Well have you tried it with the Intel compiler? doctest can compile in C++98 without any trouble and currently doesn't use thread_local anything. It uses some C++11 features only if it detects them as available. I'd be happy to address any compiler errors once reported, but I assume it should work out of the box. I might also give the compiler a go in a week or two on my machine... But I just haven't felt the need for it yet.

**Comment by smcallis** [comment]
I have tried it on Intel 13, and it was unhappy, though I can't tell you exactly why.  I'll try to get it a gist put up shortly.  I think the problem is I compile with --std=c++11 and Intel 13 reports itself as perhaps more compliant than it actually is.

**Comment by smcallis** [comment]
So testing it out today, a fair bit of the problem was on my end, I saw lots of errors and assumed it was doctest (I thought it required C++11).  Now that I know that, the only thing I had to do to get it working nicely with the Intel compiler was to disable the GCC warning pragmas if Intel is detected, and pass in -wd2196 to disablethe annoying "routing is both inline and noinline" nonsense it prints out.

**Comment by smcallis** [comment]
Yup!  I'm waiting for my revisions to get transferred somewhere I can access them, then I'll submit a PR.
