### ISSUE TITLE
Logo Proposal for Doctest

### ISSUE THREAD

**Issue by area55git** [onqtam/doctest#141]
Hi, In response to your request for Logo, I am very grateful to be able to collaborate in your project.

I need a short review about Doctest to start with the sketches. I can improve the existing one or create something totally new and different. You can tell me your suggestions.

**Comment by onqtam** [comment]
well here are some ideas:
- doctest is about testing - reliability, safety net, comfort, a green light that everything is ok after refactoring
- doctest is the lightest testing framework for C++ so perhaps something resembling speed or lightness - as a feather or a cheetah
- doctest is transparent and light - so you don't notice it - perhaps as a transparent layer on top of the production code (or depicted as a guardian angel)
- doctest is about mixing the actual production code with the tests themselves - so some mixture (like spices in a stew), or the Yin and yang
- "production code" could be depicted by some mechanical product like a steam engine? I don't know...
- doctest is very easy to get started with and use - so simplicity is also a theme

Where do you think the logo should go - at the top of the main readme?

about the size: perhaps a multiple of 888 px? that's the max width of the rendered readme's in github. Or if it is a vector image that shouldn't matter.

**Comment by area55git** [comment]
@onqtam I'm going to work on the sketches, I think I have them ready in 2 days.

**Comment by area55git** [comment]
In the next one I am working with the image of a hummingbird, because it represents speed and lightness !. I just sent you an immense unfinished so you can tell me your point of view.

![logo proposal for doctest 1](https://user-images.githubusercontent.com/38330420/43977349-dd8dfa70-9cb1-11e8-85fa-eddb8ff846b5.jpg)

**Comment by onqtam** [comment]
Sorry for the late reply!

From the first batch I like the one in the blue rectangle the most. I also like the idea with the hummingbird even more, but I initially mistook the blue version of it for water/waves/sea creature - and only later did I notice that it was a bird.

Perhaps I would need a bit more time to choose. Could the version with the hummingbird be tweaked somehow not to be confused with anything water-related?

And how would you like to proceed with the addition of the logo in the project and you being credited for it? Perhaps with a note in the main readme.md of the repository + credits in the commit message when the logo is introduced?

**Comment by area55git** [comment]
If you like the idea of the hummingbird I will continue working in that direction. Soon I will present you other sketches.

**Comment by onqtam** [comment]
I think I like the most the one with the blue background from the first batch, and also something like this:

![my_ver](https://user-images.githubusercontent.com/4648169/44194911-25441d80-a140-11e8-8769-0920fa4e7990.jpg)

So perhaps you could make a PR with both options in some vector file in the ```/scripts/data``` folder of the repo and I shall make a final choice in the coming days...? I will attribute you the same way as discussed in the [thread about dynamix](https://github.com/iboB/dynamix/issues/31).

**Comment by area55git** [comment]
Hi @onqtam 

![logo proposal for doctest](https://user-images.githubusercontent.com/38330420/44271561-74558580-a208-11e8-9a94-d282613e07b2.jpg)

**Comment by area55git** [comment]
Icon or Favicon

![logo proposal for doctest 1](https://user-images.githubusercontent.com/38330420/44272043-bcc17300-a209-11e8-985a-4d75bbd2bec7.jpg)

**Comment by area55git** [comment]
Icon or Favicon

![logo proposal for doctest 1](https://user-images.githubusercontent.com/38330420/44272176-175acf00-a20a-11e8-9663-e48cc169bc3d.jpg)

**Comment by onqtam** [comment]
Sorry for the late response - finally I choose the second option from the second batch - the one with the blue frame and the bird in the middle (I tested it how it looked in the repository page). I also choose the second from the 3 options of the favicons since it matches the logo the most.

Can you make a PR and upload it as a ```.svg``` file (in the ```/scripts/data/``` folder of the ```dev``` branch) so that I display it vectorized in the main readme?

Thanks for the great work! I will credit you the same way as [dynamix](https://github.com/iboB/dynamix#logo)

**Comment by area55git** [comment]
File Download [HERE](https://drive.google.com/open?id=14BmvvgdrhjXPym4ES8Bcn9bcAcIj8anb)

![derechos](https://user-images.githubusercontent.com/38330420/44475771-e8769b80-a603-11e8-8d71-9e98bec204ab.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
I have 2 options for the Readme folder

![readme 1](https://user-images.githubusercontent.com/38330420/44475989-7eaac180-a604-11e8-8b94-36e322b04991.jpg)
![readme 1 b](https://user-images.githubusercontent.com/38330420/44475990-7fdbee80-a604-11e8-9f0e-f3a7a86281fe.jpg)

Which one do you choose? To do the PR

**Comment by onqtam** [comment]
The first one looked better in the white readme when I tested.

**Comment by area55git** [comment]
PR #145
I had a lot of fun with this job, it's very easy to work with you. Thank you for allowing me to collaborate!

![lele 4 peq](https://user-images.githubusercontent.com/38330420/44477090-ad766700-a607-11e8-8bce-cf5859193fb3.jpg)

**Comment by onqtam** [comment]
Thanks a ton for the logo - I love it! Was easy working with you too. The logo is in the dev branch and I expect to publish the 2.0 version today in the master branch - check it out here:

https://github.com/onqtam/doctest/tree/dev

and the credits at the bottom:

https://github.com/onqtam/doctest/tree/dev#logo

**Comment by onqtam** [comment]
version 2.0 is out!

https://www.reddit.com/r/cpp/comments/99nkhw/doctest_2_released_moved_to_c11_added/
