### ISSUE TITLE
Unsigned integer overflow in fileOrderComparator

### ISSUE THREAD

**Issue by martinfinke** [onqtam/doctest#151]
Clang with `-fsanitize=undefined` shows this error message:

```
doctest.h:3635:45: runtime error: unsigned integer overflow: 84 - 280 cannot be represented in type 'unsigned int'
```

The code in question is:

```cpp
static_cast<int>(lhs->m_line - rhs->m_line);
```

where `m_line` is of type `unsigned`.

**Comment by tbleher** [comment]
Note that unsigned integer overflow is not undefined behavior (contrary to signed overflow, which is undefined), it is just flagged by Clang since it might indicate a bug.

**Comment by martinfinke** [comment]
> Note that unsigned integer overflow is not undefined behavior (contrary to signed overflow, which is undefined), it is just flagged by Clang since it might indicate a bug.

Good point. I still think this is unintended, as it's about ordering line numbers.

**Comment by onqtam** [comment]
Thanks for reporting this!

I will check it after a month since I’m away right now - only a cell phone
