### ISSUE TITLE
clang unwanted warning in user code

### ISSUE THREAD

**Issue by ASMfreaK** [onqtam/doctest#156]
See actual message in martinmoene/lest#27
Doctest has similar issue with every
`CHECK` macro.

**Comment by onqtam** [comment]
I'll check it out in a few weeks and try to fix it - sorry for the delay

**Comment by onqtam** [comment]
strange - can you give an exact case that reproduces it - code, doctest version and compiler version?

I also see that for quite some time the ```-Woverloaded-shift-op-parentheses``` warning has been suppressed for clang - see here:

https://github.com/onqtam/doctest/blob/f4e82db55c6ab572be6a69bc9d2bc2e726aa9488/doctest/doctest.h#L2018

currently all the examples are compiled with 3.5, 3.6, 3.7, 3.8, 3.9, 4, 5, 6 with all warnings enabled with ```-Weverything``` and warnings are treated as errors on the CI.

**Comment by onqtam** [comment]
I'm going to close this for now - feel free to reopen it if the issue is indeed present somehow with the latest version of the framework.
