### ISSUE TITLE
Compiler error on Android NDK r18

### ISSUE THREAD

**Issue by theodelrieu** [onqtam/doctest#163]
## Description
Hello,

I'm unable to build a test program with doctest using Android NDK r18:

```
doctest.h:4046:36: error: cannot initialize a member subobject of type 'int' with an rvalue of type 'nullptr_t'
            struct sigaction sa = {nullptr};
                                   ^~~~~~~
```

### Steps to reproduce

* [Download](https://developer.android.com/ndk/downloads/) the Android NDK r18.
* Include `doctest.h` in a `main.cpp` and compile it with the shipped `clang++` compiler

* doctest version: **v2.0.1**
* Operating System: **Debian 9 unstable**
* Compiler+version: **Clang 7.0**

**Comment by theodelrieu** [comment]
Here is a comment I found in the NDK's `bits/signal_types.h`:

```c
/* For 64-bit (and mips), the kernel's struct sigaction doesn't match the
 * POSIX one, so we need to expose our own and translate behind the scenes.
 * For 32-bit, we're stuck with the definitions we already shipped,
 * even though they contain a sigset_t that's too small. See sigaction64.
 */
```

Note that the platform that fails is Android x86_64

**Comment by onqtam** [comment]
Sooo there is a PR that fixes that - I guess it's time to merge it:

https://github.com/onqtam/doctest/pull/162

**Comment by theodelrieu** [comment]
The fix works on my machine :)

Do you plan to release a 2.0.2 soon?

**Comment by onqtam** [comment]
maybe in the following days but not today unfortunately - not sure when I'll get to it (its sort-of a lengthy process and I need my other machine for that...)

try using the dev branch for now and i'll do it when I can

**Comment by theodelrieu** [comment]
Ok thanks, I'll close this issue!
