### ISSUE TITLE
Can logging (INFO) be used in helper class outside of TEST_CASE?

### ISSUE THREAD

**Issue by marack** [onqtam/doctest#169]
I have a simple helper class that I use in a similar way to `doctest::approx` except that it allows me to check that all values in a container match.  When values from the containers do not match, I want to capture the array index where the failure occurred.

Unfortunately the `INFO()` macro seems to be ignored if it is not directly nested in a `TEST_CASE()` block.  Even calling `INFO` from a lambda which is defined within a `TEST_CASE` has no effect.

Is there a way to capture values for the currently executing test case from helper code which exists outside the scope of the `TEST_CASE` block?

**Comment by marack** [comment]
I just noticed that `MESSAGE` works in any context - this gets me 90% of the way there.  The only problem is that `MESSAGE` will print regardless of whether the test case fails.

I wonder if the inability to use `INFO` in other scopes is related to the deferred stringification?  In that case it would be great if there was a version of `INFO` which performed immediate stringification, but could be used anywhere.

**Comment by onqtam** [comment]
```INFO``` is scoped, so if you execute a lambda with a call to ```INFO```, but the asserts are outside of that lambda - the logged context will not be used. This is true for [Catch2](https://github.com/catchorg/Catch2) even though they don't have lazy stringification.

the ```CHECK_MESSAGE``` macros are just 2 macros stitched together inside - ```INFO``` and a ```CHECK``` right after it (inside of a ```{}``` block so the info is scoped).

Have a look at the [examples](https://github.com/onqtam/doctest/blob/master/examples/all_features/logging.cpp#L24) - ```INFO``` can be used in functions called from test cases, and there can be multiple active logged contexts - by nesting blocks.

Doesn't it work if you log the iteration of the loop over the container?

**Comment by marack** [comment]
I think my problem is that the `CHECK` assert is in the top level test while the `INFO` is in a function.  Now that you mention it I can see it makes sense that `INFO` is scoped so I might need to rethink the design.

I'm trying to achieve something that can be called like `CHECK(foo == approx(bar))` where both `foo` and `bar` are containers of floats and are checked element by element.  If the assertion fails the error message should indicate which index in the container failed the test.

**Comment by onqtam** [comment]
Here is some code which you can use to emulate what you need:

```c++
struct MetaInfoBool {
    bool            result;
    doctest::String meta;

    operator bool() const { return result; }
};

std::ostream& operator<<(std::ostream& stream, const MetaInfoBool& meta) {
    return stream << meta.meta;
}

template <typename T>
struct VecComparator {
    const std::vector<T>& lhs;

    VecComparator(const std::vector<T>& other)
            : lhs(other) {}

    MetaInfoBool compare(const std::vector<T>& rhs) const {
        if(lhs.size() != rhs.size()) {
            return {false, doctest::String("V1[] (length: ") + doctest::toString(lhs.size()) + ") == V2[] (length: " +
                                   doctest::toString(rhs.size()) + ")"};
        }
        for(size_t i = 0; i < lhs.size(); ++i)
            if(lhs[i] != rhs[i])
                return {false, doctest::String("V1[") + doctest::toString(i) + "] (value: " + doctest::toString(lhs[i]) +
                                       ") == V2[" + doctest::toString(i) + "] (value: " +
                                       doctest::toString(rhs[i]) + ")"};
        return {true, "V1[] == V2[]"};
    }
};
```

and use like this:
```c++
TEST_CASE("single assert for entire vector") {
    vector<int> v1 = {1, 2, 3, 4, 5, 6, 7, 8, 9};
    vector<int> v2 = {1, 2, 3, 4, 0, 0, 0, 0, 0};
    vector<int> v3 = {1, 2, 3, 4};
    
    CHECK(VecComparator<int>(v1).compare(v2));
    CHECK(VecComparator<int>(v1).compare(v3));
}
```

with the following output:

>  values: CHECK( V1[4] (value: 5) == V2[4] (value: 0) )

and

> values: CHECK( V1[] (length: 9) == V2[] (length: 4) )

In the future the framework will support matchers - there will be a few classes for comparing collections (perhaps with the option to use a predicate) available out of the box and users will also be able to write their own matchers.

**Comment by marack** [comment]
Thanks for the feedback.  I'll give that a go.
