### ISSUE TITLE
Tests that accompany code run and produce output at default

### ISSUE THREAD

**Issue by martinmoene** [onqtam/doctest#17]
In the case that unit tests accompany code, user may not expect, or like that at default 
- the tests are run,
- the test run produces output (even) if all tests pass.

If tests take a negligible amount of time, running the tests at default may be fine, provided they produce no output on success.

If tests take a non-negligible amount of time, I can imagine people like to skip the tests at default.

Provided running the test at default is retained, it would be nice if the default non-running case could be achieved through a user-supplied `main()` in combination with a new command line option `--run`, or `--unittest` (the [flag used by `D`](https://wiki.dlang.org/Unittest)).

```
int main(int argc, char** argv) {
    doctest::Context context(argc, argv); // initialize

    // overrides
    context.addFilter("no-run", !context.flag("run")); // control --no-run from --run
    ...
}
```
Note that currently configuring the context can only occur after processing the commandline options in `Context`'s constructor, hence the comment mentioning _overrides_. The lack of being able to set _defaults_ before commandline processing leads to the convoluted example above.

Supporting configuring defaults, e.g.:
```
int main(int argc, char** argv) {
    doctest::Context context;
    context.addFilter("no-run", true);  // default

    // --run (--unittest) on the commandline now overrides the --no-run default
    context(argc, argv);  // or context.apply(argc, argv);, or ...
    ...
}
```

**Comment by onqtam** [comment]
perhaps I should eliminate the ```--no-overrides``` option altogether? and allow the user to construct a ```Context``` without passing ```argc```/```argv```, then to set some options and then to apply ```argc```/```argv``` by calling ```context.applyCommandLine(argc, argv);```? What do you think about this?

**Comment by martinmoene** [comment]
Conforming to Catch's [Amending the config](https://github.com/philsquared/Catch/blob/master/docs/own-main.md#amending-the-config) as you describe above seems like a good idea.
