### ISSUE TITLE
Reduce scope of DebugOutputWindowReporter instance

### ISSUE THREAD

**Issue by bnason-nf** [onqtam/doctest#174]
Hi @onqtam,

Using doctest on Windows, I was seeing an issue with the order of global static constructors, causing the output of the DebugOutputWindowReporter to be ignored. This patch fixes that:

```diff --git a/doctest/parts/doctest_impl.h b/doctest/parts/doctest_impl.h
index c8d3d6a..80f52cc 100644
--- a/doctest/parts/doctest_impl.h
+++ b/doctest/parts/doctest_impl.h
@@ -2076,8 +2076,6 @@ namespace {
     };

     DOCTEST_THREAD_LOCAL std::ostringstream DebugOutputWindowReporter::oss;
-
-    DebugOutputWindowReporter g_debug_output_rep;
 #endif // DOCTEST_PLATFORM_WINDOWS

     // the implementation of parseFlag()
@@ -2400,6 +2398,7 @@ int Context::run() {

     // always use the debug output window reporter
 #ifdef DOCTEST_PLATFORM_WINDOWS
+    DebugOutputWindowReporter g_debug_output_rep;
     if(isDebuggerActive())
         p->reporters_currently_used.push_back(&g_debug_output_rep);
 #endif // DOCTEST_PLATFORM_WINDOWS
```

If you like, I can create a pull request for this.

Thanks,
Benbuck

**Comment by onqtam** [comment]
Thats weird - I cannot imagine what the problem could be. But it wouldn't hurt to incorporate this change - the other reporter (the console one) has its scope reduced as well anyway. I'll push a fix in the dev branch.

**Comment by onqtam** [comment]
Just pushed a "fix" in the dev branch - not sure when I'll release ```2.2.2``` but if it is important to be in an official release I'll do it. But I still cannot explain why this would be a problem - there is nothing special happening when reporters are constructed and they aren't used until ```main()``` is entered - so it's still a mystery to me.

**Comment by bnason-nf** [comment]
Hi @onqtam,

Thanks for pushing this.

The issue I'm seeing is that when `g_debug_output_rep` is at global scope is that when the constructor runs, the `oss` thread local static variable is uninitialized. I don't understand why that is though. If I change `oss` to not be thread local, then it is initialized, so maybe the thread local variables are being initialized to late in this case?

-Benbuck

**Comment by onqtam** [comment]
@bnason-nf weird... there are other thread_local globals and apparently it works OK with them... :D
Anyway this change doesn't hurt.
I'll push it in master when I release the next version - thanks for reporting!
