### ISSUE TITLE
Change the include path of the `doctest` CMake interface target so users need to specify the folder as well

### ISSUE THREAD

**Issue by ncihnegn** [onqtam/doctest#175]
I am just curious about the rationale behind using "doctest.h" instead of "doctest/doctest.h".

**Comment by onqtam** [comment]
well I don't know why the examples in the repository are done this way but the header is inside of a doctest folder itself so one may do it the way you describe if he chooses to. Looking back perhaps it should have been ```include/doctest/doctest.h``` but I don't want to introduce such changes - not really important. C++ doesn't have an approved way of structuring repositories. Perhaps for beginners it would be the easiest to just pull the header file and place it next to their only test source file.
The good thing about single-header libraries is that they are so simple and you can integrate them any way you like.

**Comment by ncihnegn** [comment]
That's true. It matters for CMake users, though. I have to change from doctest/doctest.h to doctest.h after I use target_link_library(target doctst::doctest) instead of include_directories().

**Comment by onqtam** [comment]
Well perhaps you could define the ```doctest::doctest``` target on your own 1-2 lines without needing the CMake code from doctest.

I would appreciate if others give their opinion on this issue as well before deciding if I should change anything.

**Comment by bnason-nf** [comment]
I generally prefer external libraries to use includes in the form of `<library_name/header.h>` since I feel like it hopefully reduces the potential for name collisions. On the other hand, I have no problem if doctest remains with the current structure.

**Comment by ncihnegn** [comment]
I believe <doctest/doctest.h> is the consistent way; otherwise how do you justify putting it into the doctest folder?

**Comment by onqtam** [comment]
changed in release ```2.2.2``` :)
https://github.com/onqtam/doctest/releases/tag/2.2.2

**Comment by drTr0jan** [comment]
> That's true. It matters for CMake users, though. I have to change from doctest/doctest.h to doctest.h after I use target_link_library(target doctst::doctest) instead of include_directories().

Hi @ncihnegn. I've tried to build main example from Readme via CMake ([CMakeLists.txt](https://github.com/doctest/doctest/files/12709453/CMakeLists.txt)) and have got an error.

```
boris@boris:~/doctest% cmake --build .
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
/home/boris/doctest/main.cpp:2:10: fatal error: 'doctest.h' file not found
#include "doctest.h"
         ^~~~~~~~~~~
1 error generated.
gmake[2]: *** [CMakeFiles/main.dir/build.make:76: CMakeFiles/main.dir/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

I think, it's need to specify `doctest` directory explicit for `INCLUDES DESTINATION` at: https://github.com/doctest/doctest/blob/ae7a13539fb71f270b87eb2e874fbac80bc8dda2/CMakeLists.txt#L140

If I specify `INCLUDES DESTINATION` as `${include_install_dir}/doctest`, I've got a successful build.

@onqtam, what do you think about it?
