### ISSUE TITLE
How to stop doctest hijack unhandled exceptions?

### ISSUE THREAD

**Issue by tower120** [onqtam/doctest#176]
Hi!
I would like the debugger to stop on unhandled exceptions. But doctest catch them all. 
Is it possible to temporary disable exception hijacking?

**Comment by onqtam** [comment]
Hmmm this was actually suggested long ago - so a stack trace can be obtained.

Could you try the [**DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS**](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_no_exceptions_but_with_all_asserts) config option and let me know if it is enough?

**Comment by tower120** [comment]
I'm sorry, turns out it work as is. I just had disabled breakpoints on exceptions.
