### ISSUE TITLE
Add way to override getCurrentTicks() implementation

### ISSUE THREAD

**Issue by bnason-nf** [onqtam/doctest#178]
Hi @onqtam,

One of the platforms I am using doctest on doesn't support `QueryPerformanceCounter()` or `gettimeofday()`. I added a piece to the ifdef for `getCurrentTicks()` to be able to override that with an external definition:

```diff
diff --git a/doctest/parts/doctest_impl.h b/doctest/parts/doctest_impl.h
index 3a7f6ac..acd688f 100644
--- a/doctest/parts/doctest_impl.h
+++ b/doctest/parts/doctest_impl.h
@@ -820,7 +820,14 @@ namespace {
         return false;
     }

-#ifdef DOCTEST_PLATFORM_WINDOWS
+#if defined(DOCTEST_CONFIG_GETCURRENTTICKS)
+
+    typedef uint64_t UInt64;
+
+    UInt64 getCurrentTicks() {
+        return DOCTEST_CONFIG_GETCURRENTTICKS();
+    }
+#elif defined(DOCTEST_PLATFORM_WINDOWS)
     typedef unsigned long long UInt64;
```

How would you feel about adding something like this to doctest? It definitely doesn't have to be done this way, but if there's some other supported way to provide the ticks, that would be great.

Thanks,
Benbuck

**Comment by onqtam** [comment]
I'll evaluate this tomorrow :)

**Comment by onqtam** [comment]
added in release ```2.2.2``` :)
https://github.com/onqtam/doctest/releases/tag/2.2.2
