### ISSUE TITLE
Calling convention needed on a few functions

### ISSUE THREAD

**Issue by jrouwe** [onqtam/doctest#182]
I'm compiling my project with the __vectorcall calling convention (/Gv) on MSVC which causes doctest to throw up a few compile errors:

`doctest.h(5016): error C2664: 'void qsort(void *,size_t,size_t,_CoreCrtNonSecureSearchSortCompareFunction)': cannot convert argument 4 from 'int (__vectorcall *)(const void *,const void *)' to '_CoreCrtNonSecureSearchSortCompareFunction'
doctest.h(5016): note: None of the functions with this name in scope match the target type
doctest.h(5018): error C2664: 'void qsort(void *,size_t,size_t,_CoreCrtNonSecureSearchSortCompareFunction)': cannot convert argument 4 from 'int (__vectorcall *)(const void *,const void *)' to '_CoreCrtNonSecureSearchSortCompareFunction'
doctest.h(5018): note: None of the functions with this name in scope match the target type
doctest.h(5020): error C2664: 'void qsort(void *,size_t,size_t,_CoreCrtNonSecureSearchSortCompareFunction)': cannot convert argument 4 from 'int (__vectorcall *)(const void *,const void *)' to '_CoreCrtNonSecureSearchSortCompareFunction'
doctest.h(5020): note: None of the functions with this name in scope match the target type
doctest.h(5260): warning C4007: 'main': must be '__cdecl'
`

To fix them I had to add __cdecl to the functions fileOrderComparator, suiteOrderComparator, nameOrderComparator and main.

I'm only targetting Windows and Linux so this works for me, but I don't believe OS X supports the __cdecl calling convention, so my guess is that it is best to add a macro to specify the default calling convention for those methods.

Regards,

Jorrit.

**Comment by onqtam** [comment]
Hi! I'll get to this in a few days (or perhaps a week+).

**Comment by onqtam** [comment]
I'm puzzled as to why there is a problem for ```main()``` as well and not many of the other functions... I found that imgui have had a similar issue reported, so I guess I'll do something similar for doctest: https://github.com/ocornut/imgui/issues/1230 and https://github.com/ocornut/imgui/pull/1611

**Comment by onqtam** [comment]
@jrouwe actually I just moved away from ```qsort``` and now using C++ ```std::sort``` where there shouldn't be such a problem. Also silencing the warning around ```main```.

Try the dev branch and let me know if it's fixed. Not sure when I'll release this in the master branch though...

**Comment by jrouwe** [comment]
Hello,

I can confirm that it works. Thanks for the quick fix!

Regards,
Jorrit
