### ISSUE TITLE
c++17 requirement for testing private members

### ISSUE THREAD

**Issue by YarikTH** [onqtam/doctest#188]
## Description

I tried to use new feature from #76 that was released recently and got following erorrs from compiler.
```
error C7525: inline variables require at least '/std:c++17'
error C2131: expression did not evaluate to a constant
note: a non-constant (sub-)expression was encountered
```
It seems that current feature implementation supported only for c++17. Is it possible to backport it to c++11 (c++14)?  
Another option that will work - allow to disable TEST_CASE_CLASS if c++std is less than c++17. 
Otherwise I either have to give up using TEST_CASE_CLASS  or I have to wrap every TEST_CASE_CLASS usage with macros that checks c++std version,

### Steps to reproduce

Compile example from #76, using msvc15 and c++14.

### Extra information

* doctest version: **v2.2.3**
* Operating System: **Windows 7**
* Compiler+version: **MSVC 15.0**

**Comment by onqtam** [comment]
It's not possible to backport to C++14 or 11. I'll think about disabling it, but I'm not sure if ```__cplusplus``` has the C++17 value for MSVC 2017 with ```/std:c++latest``` so I don't know if it's OK for doctest to check against ```__cplusplus```.

However You could disable it on your own however you like for now by using the following after including the doctest header:

```c++
#include <doctest.h>

#ifdef MY_CUSTOM_CONDITION

#undef TEST_CASE_CLASS
#define TEST_CASE_CLASS(...) template <typename UNUSED_T> static inline void f()

#endif
```
