### ISSUE TITLE
run test fixture from cli

### ISSUE THREAD

**Issue by nscooling** [onqtam/doctest#190]
## Description
There does not appear any ability to run a test fixture (similar to the way test cases and test suites can be run) from the command line.

I appreciate that a test-case with subcase seems to be your preferred model but not having this capability negates any major benefit of having Fixtures. 

Can it be done without prefixing all fixture test cases with an appropriate string for regex matching? 

Maybe the fixture name could be pre-pended to the test case name string to allow regex test invocation?

* doctest version: v1.2.8
* Operating System: OS X & Linux
* Compiler+version: clang & g++ C++17

**Comment by onqtam** [comment]
Hi! when using ```TEST_CASE_FIXTURE``` you are basically adding just another test case - the doctest runner doesn't know that this is in fact a special kind which derives from a class - it doesn't care.

Such test fixtures (which are normal test cases actually) can be just as easily put in a [```TEST_SUITE```](https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#test-suites) - just like normal test cases (or as you suggested a prefix in the name could be used). I could perhaps introduce a new tag [decorator](https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#decorators) and add the fixture class as a tag, but currently using test suites is an easier way and I would prefer keeping the framework simpler.

Let me know what you think.

**Comment by nscooling** [comment]
Hi Viktor, thanks for the quick response. I guess using the TEST_SUITE approach works without changing things.

I'd guess I'd like to see the Fixture treated as a TEST_SUITE so then could filter automatically at the test suite level. From a traditional test strategy perspective, I see a Fixture akin to a test suite anyway.

What would you say were the conceptual differences between a suite and a fixture?

**Comment by onqtam** [comment]
To be honest I mainly mimicked what Catch is doing (and perhaps other C++ testing frameworks).

Here is one solution you could use:
```c++
#undef DOCTEST_TEST_CASE_FIXTURE
#define DOCTEST_TEST_CASE_FIXTURE(c, ...)                                                          \
    DOCTEST_IMPLEMENT_FIXTURE(DOCTEST_ANONYMOUS(_DOCTEST_ANON_CLASS_), c,                          \
                              DOCTEST_ANONYMOUS(_DOCTEST_ANON_FUNC_),                              \
                              __VA_ARGS__* doctest::test_suite(#c))
```

and now when you use ```TEST_CASE_FIXTURE(ClassToInheritFrom, "name")``` it will be added automatically to the ```ClassToInheritFrom``` test suite, so you don't have to deal with those.

You could put that code in a header called ```doctest_proxy.h``` and have it include ```doctest.h``` and then change the semantics of the macros however you like.

Let me know if this works for you.

**Comment by nscooling** [comment]
That looks great, I'll have a play and let you know.

Thanks

**Comment by onqtam** [comment]
I missed your edit of your last post (no notification) so sorry for the late reply.

I don't think that most people would see the fixture used as a test suite.

I could add it and guard it with an ```#ifdef``` with [yet another config option](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md) but am reluctant to do so - it is a simple enough change for users to make on their own.

I might advertise the ability to change the behavior of the macros more in the docs but for now I'm closing this issue - let me know if you need anything else :)
