### ISSUE TITLE
Cppcheck 1.86 warnings

### ISSUE THREAD

**Issue by edmundvermeulen** [onqtam/doctest#198]
## Description
Cppcheck 1.86 gives the following warnings, which should be easy to fix.

[doctest.h:454] (style) Class 'String' has a constructor with 1 argument that is not explicit.[noExplicitConstructor]

Fixed by suppression:

    // cppcheck-suppress noExplicitConstructor
    String(const char* in);

[doctest.h:769] (warning) Found function call inside sizeof(). [sizeofFunctionCall]

Fixed by using decltype:

            static const bool value = sizeof(decltype(testStreamable(s << t))) == sizeof(yes);
 
 [doctest.h:1408] (style) The function 'translate' overrides a function in a base class but is not marked with a 'override' specifier. [missingOverride]

Fixed by adding override keyword:

        bool translate(String& res) const override {

### Extra information
* doctest version: v2.2.3
* Operating System: Windows 10
* Compiler+version: MS VS 2015

**Comment by onqtam** [comment]
Hi! thanks for the fix suggestions! I just pushed them in the dev branch - hopefully all compilers will be satisfied.

This will go into the master branch once I release version 2.3 which will be pretty soon - with support for reporting xml
