### ISSUE TITLE
 Get the number of passed/failed tests in the code

### ISSUE THREAD

**Issue by erelsgl** [onqtam/doctest#200]
I would like to use doctest for automatic grading of homework assignments. For this, I need to get the number of passed tests and the number of failed tests in the code, so that I can write, at the end of the main testing program, something like: "grade = passed*100/(passed + failed)". I do not need to print a report - I only need to insert this grade into a database. Is it possible?

**Comment by onqtam** [comment]
Currently you can implement a reporter: https://github.com/onqtam/doctest/blob/master/doc/markdown/reporters.md

and in that reporter in ```test_run_end()``` you can use the stats coming in the ```TestRunStats``` struct.

And then either choose your reporter from the command line with ```--reporters=my_grading_reporter``` or implement your own ```main()``` like [discussed in the docs](https://github.com/onqtam/doctest/blob/master/doc/markdown/main.md) and set the reporter like this: ```context.addFilter("reporters", "my_grading_reporter");```.

Keep in mind that version 2.3 is coming out really soon and the reporter interface might change slightly (nothing complicated). Also 2.3 will come with an xml reporter which you could use to parse more easily the test results.

**Comment by erelsgl** [comment]
Thanks! Where can I find the documentation of the TestRunStats class?

**Comment by onqtam** [comment]
it's a simple struct with a few integers - no methods:

- numTestCases
- numTestCasesPassingFilters
- numTestSuitesPassingFilters
- numTestCasesFailed
- numAsserts
- numAssertsFailed

look it up in [the header](https://github.com/onqtam/doctest/blob/master/doctest/doctest.h#L1715)

**Comment by erelsgl** [comment]
OK, thanks! This solves the problem
