### ISSUE TITLE
No DOCTEST_WITH_TESTS?

### ISSUE THREAD

**Issue by SuperWig** [onqtam/doctest#211]
Seems like you don't have the option to build the tests or not anymore?

**Comment by onqtam** [comment]
it is possible only when the doctest cmake is used directly and not through ```add_subdirectory()``` (same goes for assembling the single header).

Perhaps removing that option was a mistake - not sure.

**Comment by SuperWig** [comment]
Well I was updating the vcpkg port and noticed that there doesn't seem to be a way to disable building the tests anymore.

**Comment by onqtam** [comment]
I just re-introduced that option in this commit:
https://github.com/onqtam/doctest/commit/b22d878870de913dc15c46b3f2c35ee90d7689b2

now in master. Will move the 2.3.1 tag 1 commit ahead as well.
