### ISSUE TITLE
add example compatible with -> https://github.com/report-ci/

### ISSUE THREAD

**Issue by Milerius** [onqtam/doctest#212]
Hello, may be i'm missing something but i'm not able to make doctest work with report-ci with the new xml reporter, is this junit format right ?

**Comment by onqtam** [comment]
No, it's not. jUnit/xUnit were left for a future version - contributions are welcome!

**Comment by Milerius** [comment]
Oh glad to read this issue, I think that we can ask report-ci if we can have a doctest compatibility ! I will keep you in touch ! Thanks a lot

**Comment by onqtam** [comment]
I wrote them an email at support@report.ci 22 days ago asking if XML report is enough and still no response.

**Comment by Milerius** [comment]
We can probably open an issue on the github -> https://github.com/report-ci/scripts

**Comment by onqtam** [comment]
https://github.com/report-ci/scripts/issues/2

**Comment by Milerius** [comment]
Thanks a lot

**Comment by klemens-morgenstern** [comment]
Sorry about the lost mail, I'll check the servers ASAP.

I think we'll have doctest added within 2-3 weeks.

**Comment by klemens-morgenstern** [comment]
Done, can be closed.

Here's the code in the travis yaml https://github.com/report-ci/doctest/blob/travis/.travis.yml#L350

and in bash

```bash
my_test --reporters=xml --out=my_test.xml
# Only looks for xml files!
curl https://report.ci/upload.py | python 
```

and here's the result: https://github.com/report-ci/doctest/runs/87455527

Btw. I normally build the example by having correct tests in the master and a PR from a branch with broken tests like [here](https://github.com/report-ci/boost-example/pull/3/checks)
