### ISSUE TITLE
Data-driven testing -- print out the deepest DOCTEST_SUBCASE

### ISSUE THREAD

**Issue by jktjkt** [onqtam/doctest#215]
## Description

I'm trying to use what the Qt landscape calls a ["data driven testing"](https://doc.qt.io/qt-5/qttestlib-tutorial2-example.html). Here's my code:

```c++
TEST_CASE("converting a byte buffer to a float")
{
    float f;
    std::string buffer;

    DOCTEST_SUBCASE("0x41480000 (= 12.5)") { buffer = "\x00\x00\x48\x41"s; f = 12.5f; }
    DOCTEST_SUBCASE("0x3dcccccd (= 0.1)") { buffer = "____"s; f = 0.1f; }
    DOCTEST_SUBCASE("0x3a83126f (= 0.001)") { buffer = "\x6f\x12\x83\x3a"s; f = 0.001f; }
    DOCTEST_SUBCASE("0x43160000 (= 150.0)") { buffer = "\x00\x00\x16\x43"s; f = 150.0f; }

    auto it = buffer.cbegin();
    float result = cla::utils::parseLittleEndianBuffer<float>(it);
    REQUIRE(it == buffer.cend());
    REQUIRE(result == f);
}
```

As I'm migrating from Catch where it [required a patch](https://github.com/catchorg/Catch2/issues/734) which tweaked the test nesting that is printed out upon a failure. And indeed, it seems that a similar thing is needed with doctest. With its current `dev` branch, the test failure report only includes `"converting a byte buffer to a float"`, but it does not show that the offending data came from the `0x3dcccccd (= 0.1)` subcase:

```
[doctest] doctest version is "2.3.1"
[doctest] run with "--help" for options
===============================================================================
tests/numbers.cpp:213:
TEST CASE:  converting a byte buffer to a float

tests/numbers.cpp:225: FATAL ERROR: REQUIRE( it == buffer.cend() ) is NOT correct!
  values: REQUIRE( {?} == {?} )

===============================================================================
[doctest] test cases:      4 |      3 passed |      1 failed |      0 skipped
[doctest] assertions:    109 |    108 passed |      1 failed |
[doctest] Status: FAILURE!
```

I read the [docs about parametrized tests](https://github.com/onqtam/doctest/blob/master/doc/markdown/parameterized-tests.md). I think that the "subcases" example is a bit contrived. I actually do not mind wrapping the test data in several `DOCTEST_SUBCASE` stanzas at all; I also think that adding a nice, human-readable name to the subcase block is a nice feature.

Can this be made to work without that extra call to `CAPTURE()`?

**Comment by onqtam** [comment]
this might be the same thing: https://github.com/onqtam/doctest/issues/125#issuecomment-391321582 - there I link to the same Catch issue.

Perhaps I should really think about this - not having it on by default but at least some option... Also with the current XML output the last entered subcases could be inferred.

**Comment by onqtam** [comment]
done - for a program like this:
```c++
TEST_CASE("data-driven") {
    int a;
    SUBCASE("subcase 1")
        a = 5;
    SUBCASE("subcase 2")
        a = 42;
    CHECK(a == 6);
}
```
the output will be something like this:
```
===============================================================================
E:\doctest\scripts\playground\test.cpp:61:
TEST CASE:  data-driven

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  subcase 1

E:\doctest\scripts\playground\test.cpp:67: ERROR: CHECK( a == 6 ) is NOT correct
!
  values: CHECK( 5 == 6 )

===============================================================================
E:\doctest\scripts\playground\test.cpp:61:
TEST CASE:  data-driven

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  subcase 2

E:\doctest\scripts\playground\test.cpp:67: ERROR: CHECK( a == 6 ) is NOT correct
!
  values: CHECK( 42 == 6 )
```

that message will be printed only if the deepest subcase stack is different from the current one. Also the current subcase stack will be printed below the `TEST CASE:` as before.
