### ISSUE TITLE
DOCTEST_BREAK_INTO_DEBUGGER undefined under OSX

### ISSUE THREAD

**Issue by pthom** [onqtam/doctest#22]
Hi, 

When I use doctest with my Mac (up-to-date XCode :-), DOCTEST_BREAK_INTO_DEBUGGER is not defined.

Steps to reproduce : 
Clone https://github.com/pthom/DocTest_LibTest and compile on a mac (cmake / make)

See for example
https://github.com/pthom/DocTest_LibTest/blob/master/MyLibrary/lib1.cpp
where I had to define it in order to avoid an error

Thanks !

**Comment by onqtam** [comment]
my guess is that ```DEBUG``` (see [here](https://github.com/onqtam/doctest/blob/master/doctest/doctest.h#L128)) isn't defined when xcode is used as the generator - a friend already told me about this - I hadn't tested it - will fix.

**Comment by pthom** [comment]
Actually I was using the make generator : just type cmake then make
Hope this helps

**Comment by pthom** [comment]
Same issue if I write cmake -DCMAKE_BUILD_TYPE=Debug or Release

**Comment by pthom** [comment]
If I define DEBUG it will work.
However, my guess is that cmake defines NDEBUG for release builds, and nothing for debug builds (which is unfortunate). May be this should go in the readme.

See http://stackoverflow.com/questions/8591762/ifdef-debug-with-cmake-independent-from-platform

**Comment by ongamex** [comment]
Hmm, "NDEBUG" should be defined for non-debug build under clang and gcc if remember correctly.

**Comment by netheril96** [comment]
Wrapping `DOCTEST_BREAK_INTO_DEBUGGER` in a `#ifdef DEBUG` is really unnecessary, since the extra code generated when defined is very small,  while not defining it makes it a pain to use. People do run optimized code under debuggers. In other words, this is but a useless premature optimization. Yes, Catch does it, and that is equally pointless.

**Comment by netheril96** [comment]
In fact, the `DEBUG` guard is only present for OS X targets, but not Windows and Linux targets. An inconsistent design.
