### ISSUE TITLE
Link test runner executable into dll?

### ISSUE THREAD

**Issue by DaanDeMeyer** [onqtam/doctest#226]
When using `DOCTEST_CONFIG_IMPLEMENTATION_IN_DLL`, I linked an executable containing the test runner implementation into a shared library containing the tests but when running the executable no tests are registered. Is this a supported use case?

I'm compiling with `fvisibility=hidden` if that makes a difference.

Executable source code + cmake:

`external/doctest/main.cpp`:
```c++
#define DOCTEST_CONFIG_IMPLEMENTATION_IN_DLL
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest.h>
```

```cmake
add_executable(tests)

target_compile_features(tests PRIVATE cxx_std_11)
target_include_directories(tests PUBLIC external/doctest)
set_target_properties(tests PROPERTIES
  ENABLE_EXPORTS ON
)

target_sources(tests PRIVATE external/doctest/main.cpp)
```

`test.cpp`:

```c++
#define DOCTEST_IMPLEMENTATION_IN_DLL
#include <doctest.h>

...
```

```cmake
add_library(mylib test.cpp)
target_link_libraries(mylib PRIVATE tests)
```

**Comment by onqtam** [comment]
well such a scenario should be supported, but is the library necessary to the executable at all or is it only full of tests? Tests are self-registered upon startup but perhaps the entire library isn't necessary for the executable - try explicitly referencing a function in the executable which is defined in the dynamic library.

**Comment by DaanDeMeyer** [comment]
I got it working, had a few typos that caused problems. I also had to export and reference a function to get it to work. Thanks for the quick response.
