### ISSUE TITLE
Add custom failure messages with lazy stringification

### ISSUE THREAD

**Issue by netheril96** [onqtam/doctest#23]
Is it or will it possible to output custom messages only when `REQUIRE` or `CHECK` fails? In Catch, we can capture certain variables before doing the check, but that unnecessarily creates a string and then discards it when the test succeeds (which should be more common than failures).

**Comment by onqtam** [comment]
this is planned - it is in the [roadmap](https://github.com/onqtam/doctest/blob/dev/doc/markdown/roadmap.md) - ```INFO``` - but It will go into version 2.0 for which I cannot promise a release date. I will have to figure out the reporters API and such contextual information will have to fit the picture. I'm gearing up for a 1.1 release with fixes in the upcoming days.

Currently I don't see how to implement this without always constructing the strings - even when the assertions pass.

**Comment by onqtam** [comment]
This is implemented in the dev branch - check out the [documentation](https://github.com/onqtam/doctest/blob/dev/doc/markdown/logging.md)
