### ISSUE TITLE
Splitting templated test across different translation units

### ISSUE THREAD

**Issue by jh0x** [onqtam/doctest#238]
## Description

I am trying to split a heavy to compile test (https://github.com/jh0x/intern/tree/master/test) across several translation units to speed up the compilation. Turns out that in the final binary only one set (from one TU) of tests is fired.

### Steps to reproduce

`main.cpp`:
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>
```
`t.h`
```cpp
#include <doctest/doctest.h>
TEST_CASE_TEMPLATE_DEFINE("foo", T, test_id)
{
    T t = 1;
    REQUIRE(t == 1);
}
```

`t0.cpp`
```cpp
#include "t.h"
TEST_CASE_TEMPLATE_INVOKE(test_id, int);
```

`t1.cpp`
```cpp
#include "t.h"
TEST_CASE_TEMPLATE_INVOKE(test_id, long);
```

After compiling, linking and running 1 test case is invoked.

Alternatively, if we did only this instead:
`t.cpp`
```cpp
#include "t.h"

TEST_CASE_TEMPLATE_INVOKE(test_id, int);
TEST_CASE_TEMPLATE_INVOKE(test_id, long);
```
Two test cases are getting invoked.

### Extra information

* doctest version: b6dbff7c (2.3.2)
* Operating System: Fedora 29, X64
* Compiler+version: clang version 7.0.1 (Fedora 7.0.1-6.fc29), g++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by onqtam** [comment]
Thanks for reporting! I reproduced it with MSVC as well. I'll look into it asap. curiously if we add a single blank line in one of the 2 source files before the INVOKE call it works properly.
