### ISSUE TITLE
doctest given defined with short macro name

### ISSUE THREAD

**Issue by m-bd** [onqtam/doctest#239]
It should be defined with the long name.
It is not defined otherwise (if no short macro names).

https://github.com/onqtam/doctest/blob/b6dbff7c5576a5f377caa7c5f53f01df3c479827/doctest/doctest.h#L2514

**Comment by onqtam** [comment]
Thanks for catching this! I'll fix it at some point in the dev branch - burried in work currently. PRs welcome!

**Comment by m-bd** [comment]
I’ll send a PR when I get back home.
