### ISSUE TITLE
Only one SUBCASE per line is executed

### ISSUE THREAD

**Issue by wichtounet** [onqtam/doctest#25]
I found an important difference with Catch: Only one SUBCASE per line is executed. 

For instance, this test case: 

```c++
TEST_CASE("lines") {
    SUBCASE("A"){ std::cout << "a";} SUBCASE("B"){ std::cout << "a"; }
}
```

Will only print "a" and not "aa". Catch (with SECTION) executes correctly both sections. 

This makes a big difference when you are using SUBCASE in a macro. In which case, you'll have several SUBCASE per line once the preprocessor is done. I'm using this to create templated test case. This work well with Catch, but does not work with doctest. 

This probably comes from the fact that pairs of files and lines are stored in subcasesPassed instead of triple of files, lines and names.

**Comment by onqtam** [comment]
another thing I hadn't thought of :)

yes - that is the reason - I will add the name of the macro too - but even then It might fail when no name is given - but still it would be better than now. Thanks!
