### ISSUE TITLE
Windows Clang GNU command line warnings

### ISSUE THREAD

**Issue by DaanDeMeyer** [onqtam/doctest#253]
I'm back with more warnings from an even more obscure setup.

CMake 3.15 just released with support for using clang/clang++ on Windows instead of clang-cl. Compiling doctest with this results in a few issues:

1. clang++ on Windows needs to be in C++14 mode to work with MSVC stdlib headers.

We can solve this by setting the `doctest_with_main` standard to C++14 if this specific setup is     used.

2. Some unused macro warnings:

```
../doctest/parts/doctest.cpp:3:9: warning: macro is not used [-Wunused-macros]
#define DOCTEST_LIBRARY_IMPLEMENTATION
        ^
../doctest/parts/doctest.cpp:130:9: warning: macro is not used [-Wunused-macros]
#define VC_EXTRA_LEAN
        ^
```

I'm not sure if these are false positives or actually valid.

3. A non-portable system include warning:

```
../doctest/parts\doctest.cpp:140:10: error: non-portable path to file '<Windows.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-system-include-path]
#include <windows.h>
         ^~~~~~~~~~~
         <Windows.h>
```

**Comment by onqtam** [comment]
wow - the unused macro ```DOCTEST_LIBRARY_IMPLEMENTATION``` warning is weird - it's a standard include guard technique... maybe the compiler distinguishes between .cpp and .h files and reports it only for defines from a .cpp file......
