### ISSUE TITLE
Register a listener(reporter) that always listens

### ISSUE THREAD

**Issue by claremacrae** [onqtam/doctest#257]
## Description

Currently, registering a new reporter only works if the program's command-line arguments request the new reporter.

This is great for a reporter, but it doesn't allow for a subscription model.

For ApprovalTests.cpp, we are looking to say `REGISTER_LISTENER(MyReporter)` - that will always listen, and not interfere with any use of `--reporter` on the command line.

### Steps to reproduce

If you call `REGISTER_REPORTER()` without the use of `--reporter=`, your listener is not used.

### Extra information

We (@isidore and I) would love to have a 10 minute Skype call with you, if you are interested.

We are doing this as someone has asked us to make ApprovalTests.cpp support doctest: https://github.com/approvals/ApprovalTests.cpp/issues/11

**Comment by claremacrae** [comment]
On reflection, having looked at the Catch2 code more closely, I see that Catch has two separate concepts, Listener and Reporter.

Catch2 listeners are registered with `CATCH_REGISTER_LISTENER()` - and are always active. That's what we are using with ApprovalTests.cpp's Catch integration.

Catch2 reporters are selectable by the user at run-time, depending on their needs...

If I understand correctly, doctest has combined these two features in to one - hence this question.

**Comment by onqtam** [comment]
I think it should be doable like this:

```c++
context.addFilter("reporters", "my-listener");
context.addFilter("reporters", "console");
// and then call
context.applyCommandLine(argc, argv);
```

when providing a [custom main](https://github.com/onqtam/doctest/blob/master/doc/markdown/main.md).

But I'm not sure if that way the console reporter will be replaceable - perhaps the API isn't sufficient yet. Thanks for reporting this - I'll think about it some more when I have the time.

**Comment by onqtam** [comment]
I just pushed this in the dev branch - just use ```REGISTER_LISTENER``` instead of ```REGISTER_REPORTER``` - the behavior will be the same as in Catch2: all listeners will be executed before any reporter, and cannot be filtered through the command line.

**Comment by claremacrae** [comment]
Thanks! I read the differences in the docs, and I understand the changes because of this request...

I'd be happy to make some minor clarifications to the new docs if you'd be interested - what would be the most convenient way for me to do this? 

Comments on the commit?
Fork the repo and make a PR on the dev branch?
Anything else?

**Comment by claremacrae** [comment]
Or pair?

**Comment by onqtam** [comment]
Sorry I left the office. Whichever is easiest for you - comments on the review work too :)

**Comment by claremacrae** [comment]
I can confirm that when I build ApprovalTests.cpp against the doctest single header on its dev branch, and change `REGISTER_REPORTER` to `REGISTER_LISTENER`, I can then switch to using the following, and can delete our custom main altogether.

```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest.hpp>
```

This is tremendous - thanks very much indeed.

I know you're busy, but do you have any idea when you might do your next release, please?

It would be lovely to get this included in ApprovalTests.cpp before I head off for CppCon, to plug the doctest integration as part of my talk there... :-)

**Comment by claremacrae** [comment]
I've also confirmed that the existing reporter mechanism works fine when I have registered a Listener as described above.

For example, running our tests with `--reporters=console,xml` does do invoke our listener, and does also write out the output of the `console` and `xml` reporters. :-)

**Comment by claremacrae** [comment]
As far as I'm concerned, this feature is good to go, and the issue could be closed - thank you again for implementing this! /CC @isidore

**Comment by onqtam** [comment]
I'll release an official version hopefully within 1-2 weeks - way before CppCon :)

**Comment by claremacrae** [comment]
That’s ideal - thank you!
