### ISSUE TITLE
Illegal syntax for decorators compiles and runs without warning, but has no effect

### ISSUE THREAD

**Issue by zhihaoy** [onqtam/doctest#264]
## Description

```
TEST_CASE("my case", test_suite("costly")) { ... }
```

The `*` operator should be used instead, but the above code compiles and runs, which causes confusion (for example, `-tse=costly` does nothing to the end-users).

**Comment by onqtam** [comment]
Which compiler are you using? The ```DOCTEST_TEST_CASE``` macro has a single argument and when I use GCC on my local linux box it properly errors about the extra argument.

**Comment by zhihaoy** [comment]
MSVC.  Ahh, this time I do see a warning:

```
warning C4002:  too many arguments for function-
like macro invocation 'DOCTEST_TEST_CASE'
```

I wasn't expecting a warning.  Sorry about that.

There is a way to dispatch on fixed numbers of arguments in macros, which can make `TEST_CAST("name", test_suite("suite") * skip())` work.
