### ISSUE TITLE
CHECK_EQ with enum values

### ISSUE THREAD

**Issue by killkrt** [onqtam/doctest#276]
## Description
I don't know if it could be a bug or it is more a feature request.
Anyway if you compare two enum values using `CHECK_EQ` and the check fails, the error message shows question mark instead of values.

I would expect that the enum values are casted to integer by default. Or maybe to  have a macro (e.g.: `CHECK_EQ_ENUM`) that automatically cast to int.

## Extra info
* doctest version: 2.3.3
* Operating System: Arch Linux x86_64 5.2.9
* Compiler+version: clang 8.0.1

**Comment by onqtam** [comment]
This is a duplicate of this: https://github.com/onqtam/doctest/issues/121

**Comment by Trass3r** [comment]
Yes looks like a duplicate.

**Comment by onqtam** [comment]
closing this one since #121 has been implemented & closed
