### ISSUE TITLE
Customize test names / variable substitution

### ISSUE THREAD

**Issue by dhardtke** [onqtam/doctest#284]
## Description
This might be a feature request as I have not found any way to do this using existing features.

Suppose I have a test case like this:
```cpp
TEST_CASE ("Dynamic values") {
    std::random_device dev;
    std::mt19937 rng(dev());
    std::uniform_int_distribution<std::mt19937::result_type> dist(1, 21);

    for (int i = 0; i < 20; i++) {
        int n = dist(rng);
        int reference = fib(n);
        CHECK_MESSAGE(fibonacci(n) == reference, "fibonacci(" << n << ") should be " << reference);
    }
}
```

When the test is executed I get `ERROR: CHECK( fibonacci(n) == reference ) is NOT correct!`. Is there any way to substitute the `n` variable in the message?

**Comment by onqtam** [comment]
Doesn't the code you pasted work? Isn't there something like this on the next 2 lines after what you showed:
```
test.cpp:6: ERROR: CHECK( fibonacci(n) == reference ) is NOT correct!
  values: CHECK( 123 == 143 )
  logged: fibonacci(n) should be...
```
Where ```n``` is exactly what you care about?

**Comment by dhardtke** [comment]
I am using the XML reporter and the test name there is just `fibonacci(n) == reference`.
I am trying to find a way to make the `n` be substituted in the test name.

**Comment by onqtam** [comment]
For this example from doctest: https://github.com/onqtam/doctest/blob/master/examples/all_features/logging.cpp#L20
The XML output is the following: https://github.com/onqtam/doctest/blob/master/examples/all_features/test_output/logging.cpp_xml.txt#L6

Note the ```<Info>``` after ```<Original>``` and ```<Expanded>```

Isn't there something like that in your xml output?

**Comment by onqtam** [comment]
I can't think of a way to add ```n``` as an integer in the assert string representation.

What the ```CHECK_MESSAGE(cond, msg << var << msg2);``` expands to is the following:
```
{
    INFO(msg << var << msg2);
    CHECK(cond);
}
```

and in the report doctest will stringify ```cond``` by using the ```#``` preprocessor operator and will also stringify the value of ```cond```, but if ```cond``` is a ```function(arg)``` it will only stringify the result of that function and not the argument as well.

```INFO()``` is the only mechanism in doctest for logging additional information and that is what's behind ```CHECK_MESSAGE```.

**Comment by onqtam** [comment]
@dhardtke I'm thinking of closing this issue soon - let me know if there are any further questions.
