### ISSUE TITLE
CHECK_THROWS_AS of non-default constructor wants to call default constructor

### ISSUE THREAD

**Issue by mika-fischer** [onqtam/doctest#293]
### Steps to reproduce
```cpp
#include <doctest.h>
#include <exception>

struct foo {
    foo() = delete;
    foo(int);
    int bar();
};

TEST_CASE("foo") {
    int i = 0;
    SUBCASE("empty") {
        CHECK_THROWS_AS(foo(i), std::exception); // error: use of deleted function 'foo::foo()'
    }
    SUBCASE("bar") {
        CHECK_THROWS_AS(foo(i).bar(), std::exception); // works
    }
    SUBCASE("empty") {
        CHECK_THROWS_AS(foo(int(i)), std::exception); // works
    }
}
```
See https://godbolt.org/z/7t32D-

### Extra information
* doctest version: **v2.3.4**

**Comment by onqtam** [comment]
Did that help?

Btw even without doctest you would get an error if you just wrote ```foo(i);``` in function scope, but if you cast it to void like this: ```(void)foo(i);``` it works. I'm thinking of closing this issue...

**Comment by mika-fischer** [comment]
Sorry, I forgot about this. I rolled back the conversion from catch2 to doctest because of the missung GENERATE feature, so I didn't get around to testing this...

But the suggested fix works, thanks. Maybe this should be the default?
