### ISSUE TITLE
[feature request] Assertion macros for throwing exception of a specific type with message - <LEVEL>_THROWS_WITH_AS(expr, string, ex_type)

### ISSUE THREAD

**Issue by kkarbowiak** [onqtam/doctest#295]
## Description
There are already very useful macros for asserting:

 * a specified type of exception is thrown (`<LEVEL>_THROWS_AS`)
 * an exception is thrown with specified message (`<LEVEL>_THROWS_WITH`)

What I miss is the combination of the two, that is macros for asserting an exception of specified type is thrown with a specified message, for example:

 * `<LEVEL>_THROWS_AS_WITH`(expression, exception_type, c_string)

**Comment by onqtam** [comment]
I just pushed this in the dev branch and will try to release a new version officially soon. The new macros are called ```<LEVEL>_THROWS_WITH_AS``` instead of "...AS_WITH" because the type of the exception needed to be the last of the macro arguments, because it is a ```...``` var arg.

**Comment by kkarbowiak** [comment]
Thanks a lot! I was slowly looking for ways to do it myself and send a pull request, but now I don't have to.
