### ISSUE TITLE
Warning: C26812: The enum type 'doctest::assertType::Enum' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).

### ISSUE THREAD

**Issue by Chaiomanot** [onqtam/doctest#298]
* doctest version: **commit 7ac22cc**
* Compiler+version: **MSVC 2019**

Compiler produces warning:

> C26812: The enum type 'doctest::assertType::Enum' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).

**Comment by onqtam** [comment]
this has been fixed in the dev branch - will release an official version with this at some point. Thanks for reporting :)
