### ISSUE TITLE
Does some equivalent features from google test exist here?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [onqtam/doctest#300]
## Description

Does some equivalent features from google test exist here? Features like
1.  EXPECT_CALL
1.  testing::Test

Just trying this doctest. Very nice.

Oh by the way, do you have like a forum that I can ask? Not sure where to ask so I ask here.

**Comment by onqtam** [comment]
unfortunately EXPECT_CALL is part of google mock. doctest doesn't provide any moching capabilities, but some mocking frameworks have been made to work with doctest - see [here](https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#is-mocking-supported) (and I guess google mock could be integrated).

about testing::Test - I guess that's the base class for creating fixtures - doctest supports those [as well](https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#test-fixtures) but it also provides a better way of sharing setup and teardown code called [subcases](https://github.com/onqtam/doctest/blob/master/doc/markdown/tutorial.md#test-cases-and-subcases).

Github issues are fine for such questions but you could also make use of our [gitter channel](https://gitter.im/onqtam/doctest) :)

Let me know if this answers your questions :)

**Comment by syaifulnizamyahya** [comment]
Thank you for answering my question and providing alternatives.
