### ISSUE TITLE
Skip subcase

### ISSUE THREAD

**Issue by websocket98765** [onqtam/doctest#304]
## Description

This is a question and possible feature request.

Is it possible to skip subcases? 

From the docs, it appears that only TEST_SUIT and TEST_CASE can be skipped. https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#decorators

The use case for this is the ability to skip the smallest unit of test, as opposed to needing to skip a TEST_CASE which may contain multiple SUBCASE's. 

### Extra information

* doctest version: 2.3.5
* Operating System: Linux
* Compiler+version: gcc 9.2

**Comment by onqtam** [comment]
You could do that using the ```--subcase-exclude=<pattern>``` [command line](https://github.com/onqtam/doctest/blob/master/doc/markdown/commandline.md) option to filter specific subcases by name (and could also [provide your own main()](https://github.com/onqtam/doctest/blob/master/doc/markdown/main.md) where you set that filter by default).

Let me know if this helps :)

**Comment by websocket98765** [comment]
Very helpful! I'll probably set up something like this to have consistency and brevity for all three:
```
./test --test-suite-exclude="*_SKIP_*" --test-case-exclude="*_SKIP_*" --subcase-exclude="*_SKIP_*"
```

(Something like that could make a good default filter. From a user perspective, it would make test code a tad cleaner than `* doctest::skip(true)` and is super easy to remember how to skip tests.)

Thanks for the tip!

**Comment by amdjachenko** [comment]
I have similar needs, but I would like to skip subcase conditionally based on the result of previous subcase(s). More specifically, I have a static variable in a WHEN section that contains 2 THEN sections. When first THEN passes at the last statement is sets data to the static variable. The following THEN section should only run if that variable is set. The first idea that came to my mind was like THEN("name" * doctest::skip(!!staticVar)) but decorators only work with TEST_CASE but not with subcases.

In my case I test serialization/deserialization pair of method. So if serialization fails then there is no sence to test deserialization. Also I uses output made by serialization as input for deserialization. I understand it is not easy to pass data from one subcase to another so static variable is ok for me as a workaround. Sure I can add simple check of static variable inside the second THEN and just return if it is not set, but I would like that the subcases isn't run instead to not polute/lie in output about success of the second THEN subcase.

**Comment by obewan** [comment]
I've try to do SUBCASE("My test" * doctest::skip(true)) thinking it will work but it doesn't, could be great if it could work.
