### ISSUE TITLE
CMake: cannot install target doctest_with_main

### ISSUE THREAD

**Issue by theodelrieu** [onqtam/doctest#310]
Hello,

I'm currently trying to package doctest for [conan-center-index](http://github.com/conan-io/conan-center-index), but I'm struggling with the target `doctest_with_main`, which has the property `EXCLUDE_FROM_ALL`.

This property prevents the target from being installed normally. Is this a wanted behavior?

**Comment by onqtam** [comment]
I don't think it's necessary to package ```doctest_with_main``` - the user could easily make some ```.cpp``` file and just define ```DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN``` before including ```doctest.h```.

The ```EXCLUDE_FROM_ALL``` property is there so it doesn't get compiled by default when the ```CMakeLists.txt``` is used as a subproject - not everyone would need it.

**Comment by onqtam** [comment]
I'm closing this since I don't think anything more needs to be done here :)
