### ISSUE TITLE
Mistake in generator with lgtm error

### ISSUE THREAD

**Issue by RevoluPowered** [onqtam/doctest#311]
https://github.com/onqtam/doctest/blob/b22d878870de913dc15c46b3f2c35ee90d7689b2/scripts/cmake/assemble_single_header.cmake#L6

**Comment by RevoluPowered** [comment]
Has lgtm [cpp/missing-header-guard] error

**Comment by onqtam** [comment]
that is there intentionally - is that a problem somehow? I suppress many warnings of different static analysis tools and this one in particular is for this: https://lgtm.com/projects/g/onqtam/doctest/context:cpp

**Comment by RevoluPowered** [comment]
oh no it was just in our doctest.h and thought it was an issue
