### ISSUE TITLE
the FAQ about difference to Catch2 is missing tags

### ISSUE THREAD

**Issue by TooManyDots** [onqtam/doctest#315]
In Catch2 you can add tags to your test-cases e. g.

```cpp
TEST_CASE("test-name", "[first_tage][second_tag]" ) {
...
}
```

As far as I can see doctest doesn't have this. You can also selectively run tests based on tags.

**Comment by onqtam** [comment]
perhaps I should put a separate bullet point for it (apart from ```other small stuff```). There's an example how to easily convert Catch2 test cases using tags to doctest test cases there.
