### ISSUE TITLE
Doctest SEH handlers are called before __except handlers

### ISSUE THREAD

**Issue by jkriegshauser** [onqtam/doctest#324]
## Description
Doctest will report exceptions even if code exists that uses Windows `__try`/`__except` Structured-Exception Handlers.

### Steps to reproduce
This test case will report a SIGSEGV even though the crash is handled by SEH:
```
#ifdef _MSC_VER
static void NoCrash()
{
    __try
    {
        int* p = 0;
        *p = 1;
    }
    __except (1)
    {
        // Caught!
    }
}

TEST_CASE("SEH Avoided Crash")
{
    NoCrash();
    CHECK(1);
}
#endif
```

### Extra information

* doctest version: **v2.3.6**
* Operating System: **Windows 10 x64**
* Compiler+version: **MS Visual Studio 2017**

**Comment by TheQwertiest** [comment]
@onqtam , shouldn't be this issue closed, since https://github.com/onqtam/doctest/pull/325 fixed it?

**Comment by onqtam** [comment]
@TheQwertiest It's being kept open since it's still not pushed to master (only in dev)
