### ISSUE TITLE
Noreturn and noexcept defines for Visual Studio 2013 support

### ISSUE THREAD

**Issue by robloh** [onqtam/doctest#327]
## Description
I need support for VS 2013 and discovered this can be achieved with a few small changes instead of defining DOCTEST_CONFIG_NO_EXCEPTIONS which removes support for REQUIRE

### Steps to reproduce
1) define DOCTEST_THREAD_LOCAL (not documented)
2) remove [[noreturn]] and noexcept uses from doctest.h
3) compile with VS 2013

### Extra information
I propose defines are implemented for [[noreturn]] and noexcept in the same way as DOCTEST_THREAD_LOCAL is done so VS 2013 (and compilers like it that have partial C++11 support) can be used by simply defining these before including doctest.h

I am willing to submit a pull request if the above approach sounds good.

* doctest version: **v2.3.6**

**Comment by onqtam** [comment]
Sorry for the late reply - yes, a PR would be good! Make it against the ```dev``` branch. I guess it would be something like this:

```c++
#ifndef DOCTEST_NORETURN
#define DOCTEST_NORETURN [[noreturn]]
#endif

#ifndef DOCTEST_NOEXCEPT
#define DOCTEST_NOEXCEPT noexcept
#endif
```

These things don't have to be documented - just like ```DOCTEST_THREAD_LOCAL``` isn't.
