### ISSUE TITLE
Can I inherit ConsoleReporter?

### ISSUE THREAD

**Issue by erelsgl** [onqtam/doctest#344]
## Description
I tried to write a new reporter by inheriting ConsoleReporter and modifying some functions. I wrote this in a new file:

    #include "doctest.h"
    using namespace doctest;
    struct ReporterGrader: public ConsoleReporter {
         ...
    };

But the compiler gave me an error "expected class name", as if it does not recognize ConsoleReporter. What am I doing wrong?

### Extra information
* doctest version: **v2.3.7**
* Operating System: **Windows 10 / WSL**
* Compiler+version: **clang++5.0**

**Comment by onqtam** [comment]
Well first the console reporter class is in the ```doctest::detail``` namespace, and also it's only visible in the translation unit where you have implemented the framework (where you have defined ```DOCTEST_CONFIG_IMPLEMENT``` before including the header) - there you could inherit from it, register it as a different reporter (perhaps ```my_new_console```) and then use that through the ```--reporter=my_new_console``` command line option. Does this help?

**Comment by erelsgl** [comment]
Indeed it works in the main translation unit, but I did not find it in the "detail" namespace but in the "doctest" namespace. Here is a main program that works for me:
```

#define DOCTEST_CONFIG_IMPLEMENT
#include "doctest.h"
using namespace doctest;

struct ReporterGrader: public ConsoleReporter {
    ReporterGrader(const ContextOptions& opt): ConsoleReporter(opt) {}

    void test_run_end(const TestRunStats& run_stats) override {
        ConsoleReporter::test_run_end(run_stats);
        float grade = (run_stats.numAsserts - run_stats.numAssertsFailed) * 100 / run_stats.numAsserts;
        std::cout << "Grade: " << grade << std::endl;
    }
};

REGISTER_REPORTER("grader", /*priority=*/1, ReporterGrader);

int main(int argc, char** argv) {
    Context context;
    context.addFilter("reporters", "grader");
    context.run();
}

```

**Comment by onqtam** [comment]
Glad that it worked! The class is actually in the detail namespace but that namespace gets used in an anonymous namespace inside of the doctest namespace and that's why you find it in ```doctest```.

I'm closing this as the issue seems resolved :)
