### ISSUE TITLE
Any option to show each test case's execute time?

### ISSUE THREAD

**Issue by foobra** [onqtam/doctest#358]
## Description
Any option to show each test case's execute time? Just want to print them out in log

* doctest version: 2.3.7
* Operating System: mac
* Compiler+version: Apple clang version 11.0.0 (clang-1100.0.33.17)

**Comment by onqtam** [comment]
sure, use ```-d``` or ```--duration``` from the [command line](https://github.com/onqtam/doctest/blob/master/doc/markdown/commandline.md) :)

Let me know if the output is sufficient - it should behave the same way as Catch2.
