### ISSUE TITLE
Warning c6319 in Visual Studio

### ISSUE THREAD

**Issue by Cvelth** [onqtam/doctest#359]
## Description
Visual Studio marks asserts with [warning c6319](https://docs.microsoft.com/en-us/cpp/code-quality/c6319?view=vs-2019).

### Steps to reproduce
- `$ git clone https://github.com/Cvelth/cpp_starter_fork`
- `$ cmake.exe -Htest -Bbuild -G "Visual Studio 16 2019"`
- open `build/GreeterTests.sln`
- navigate to `GreeterTests/Source Files/greeter.cpp`
![image](https://user-images.githubusercontent.com/18015148/80123382-810ead00-8597-11ea-8902-7d77646cc586.png)
![image](https://user-images.githubusercontent.com/18015148/80123926-317cb100-8598-11ea-9d47-a0c107a9fbaa.png)

### Extra information
* doctest version: **v2.3.7**
* Operating System: **Windows 10 (1909, build 18363.778)**
* Compiler+version: **Microsoft Visual Studio 2019 (16.5.1) with MSVC 19.25.28611.0**

**Comment by onqtam** [comment]
There's no way to make all the static code analysis tools happy... I used the `do { ... } while((void)0, 0)` trick to avoid warnings because `do { ... } while(false)` was a problem with some other compilers... But it seems that the latest MSVC complains about this.

**Comment by Cvelth** [comment]
Can confirm that `do { ... } while(false) resolves the issue and works great. Not sure about other compilers, though.

**Comment by onqtam** [comment]
I'll probably do a push in a test branch to see what the CI reports (if all supported compilers are fine with that) but I can't promise that will happen soon.

**Comment by Cvelth** [comment]
I doesn't seem to cause any problems ([proof](https://github.com/Cvelth/doctest/tree/while_false)).
The only `failing` build seems to be a compiler issue (a typo in a header file), which should be fixed with the release of `visual studio 16.6` (`msvc 14.26`), as it's already fixed in `16.6 preview 2`. Proofs: [1](https://developercommunity.visualstudio.com/comments/977177/view.html), [2](https://developercommunity.visualstudio.com/comments/977177/view.html).

**Comment by onqtam** [comment]
Lol a typo in a header file... :D

Well ok, that sounds reasonable. You can open a PR from your branch and we'll see if all the builds pass (including travis & appveyor - besides just github actions)

**Comment by Cvelth** [comment]
`Travis CI` and `Appveyor` both pass.
![image](https://user-images.githubusercontent.com/18015148/80308754-6297f400-87d9-11ea-822c-9219cc33dbd0.png)
![image](https://user-images.githubusercontent.com/18015148/80308803-9e32be00-87d9-11ea-9168-ca450c8a05bf.png)

I was hesitant to open PR as it does fail on a single build-system.

**Comment by onqtam** [comment]
I don't see how your changes could be triggering that failure - I also just looked at the previous github actions builds of doctest and seems that this failure is already present: https://github.com/onqtam/doctest/actions

So a PR would be just fine :)

**Comment by Cvelth** [comment]
Should I PR changes after the target `assemble_single_header` is run, or just `doctest_fwd.h` changes?

**Comment by onqtam** [comment]
preferably after that target has run - I like to keep the resulting header in sync, but it's not a deal-breaker.
