### ISSUE TITLE
Linking problem with Clang 10 on Windows

### ISSUE THREAD

**Issue by h5rdly** [onqtam/doctest#362]
On Windows 10 64bit (`MSVC 16.6`  installed with their `Build Tools` installer):

```
clang version 10.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

For the tutorial code in `test.cpp`:

```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

int factorial(int number) { return number <= 1 ? number : factorial(number - 1) * number; }

TEST_CASE("testing the factorial function") {
    CHECK(factorial(1) == 1);
    CHECK(factorial(2) == 2);
    CHECK(factorial(3) == 6);
    CHECK(factorial(10) == 3628800);
}
```
With `clang++ -o test.exe test.cpp`, I get:

```
# clang++ -o test.exe test.cpp
test-94ae87.o : error LNK2019: unresolved external symbol fileno referenced in function "void 
__cdecl doctest::`anonymous namespace'::color_to_stream(class std::basic_ostream<char,struct 
std::char_traits<char> > &,enum A0xEEF7E3AD::Color::Enum)" (?color_to_stream@?
A0xEEF7E3AD@doctest@@YAXAEAV?$basic_ostream@DU?
$char_traits@D@std@@@std@@W4Enum@Color@1@@Z) test-94ae87.o : error LNK2019: 
unresolved external symbol isatty referenced in function "void __cdecl doctest::`anonymous 
namespace'::color_to_stream(class std::basic_ostream<char,struct std::char_traits<char> > &,enum 
A0xEEF7E3AD::Color::Enum)" (?color_to_stream@?A0xEEF7E3AD@doctest@@YAXAEAV?
$basic_ostream@DU?$char_traits@D@std@@@std@@W4Enum@Color@1@@Z) 
test.exe : fatal error LNK1120: 2 unresolved externals
clang++: error: linker command failed with exit code 1120 (use -v to see invocation)
```

Or, with clang's linker via `-fuse-ld=lld` : 

```
lld-link: error: undefined symbol: fileno
>>> referenced by C:\Users\bobo\AppData\Local\Temp\test-57d48b.o:(void __cdecl doctest::`anonymous 
namespace'::color_to_stream(class std::basic_ostream<char, struct std::char_traits<char>> &, 
enum 0xEEF7E3AD::Color::Enum))

lld-link: error: undefined symbol: isatty
>>> referenced by C:\Users\bobo\AppData\Local\Temp\test-57d48b.o:(void __cdecl doctest::`anonymous
 namespace'::color_to_stream(class std::basic_ostream<char, struct std::char_traits<char>> &, 
enum 0xEEF7E3AD::Color::Enum))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I add  `#define DOCTEST_CONFIG_COLORS_NONE` above `#include "doctest.h"`, works fine.

**Comment by Sahnvour** [comment]
Hello,

The problem is not actually related to doctest. You are having these errors because the linker can't find the libraries it needs (in this case, the crt). When compiling C++ on windows you usually want to call the build from the [native tools command prompt](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019) that will setup the environment correctly for you.
Hope it helps.

**Comment by h5rdly** [comment]
Sorry, I'm relatively new to this. You're saying there's no way to make clang find this crt library?

**Comment by Sahnvour** [comment]
Yes there is, you just need to call your compiler (or the script calling it) from the native tools command prompt. That's just a classic windows console but with environment variables set up that the compiler and linker will pick up. Check the documentation I linked, it's well detailed.

**Comment by h5rdly** [comment]
Thanks, but I don't want to install more MS build tools, the SDK / MSVC took enough gigs. 

Is it possible to somehow load this crt library location manually with the clang command?

**Comment by Sahnvour** [comment]
You already have it since you installed the build tools.

**Comment by luandinamo** [comment]
To fix this change the deprecated (on windows) `isatty` and `fileno` to `_isatty` and `_fileno`. 
It will work on _clang++_ and _cl.exe_.

from
```
#ifdef DOCTEST_CONFIG_COLORS_WINDOWS
        if(g_no_colors ||
           (isatty(fileno(stdout)) == false && getContextOptions()->force_colors == false))
            return;
```

to
```
#ifdef DOCTEST_CONFIG_COLORS_WINDOWS
        if(g_no_colors ||
           (_isatty(_fileno(stdout)) == false && getContextOptions()->force_colors == false))
            return;
```
