### ISSUE TITLE
Memory sanitizer fails.

### ISSUE THREAD

**Issue by Cvelth** [onqtam/doctest#365]
## Description
Included with `clang` memory sanitizer fails when running the tests: [link to a workflow output](https://github.com/Cvelth/doctest_fork/runs/637101707?check_suite_focus=true) ([*.yml](https://github.com/Cvelth/doctest_fork/blob/sanitizer/.github/workflows/memory_sanitizer.yml))

### Steps to reproduce
Run tests with memory sanitizer enabled (`-fsanitize=memory` on `clang`).

### Extra information
* doctest version: **`dev` branch**
* Operating System: **ubuntu-latest (Github Actions)**
* Compiler+version: **`Clang 9.0.0` / `Clang 10.0.0`**

**Comment by Cvelth** [comment]
Update: seems like it's an issue with `libc++`, as something as simple, as this produces the same error:
```#include <iostream>
int main() {
	std::cout << "\033[0;36msome text" << std::endl;
}```

![image](https://user-images.githubusercontent.com/18015148/80850002-58835480-8c22-11ea-8b32-4c8c8c6be904.png)

**Comment by onqtam** [comment]
The stdlib needs to be instrumented with MSAN as well :)
https://github.com/onqtam/doctest/issues?q=memory+sanitizer

**Comment by Cvelth** [comment]
Sorry for a false positive. Thanks for the correction.
