### ISSUE TITLE
How to override file_line_to_stream?

### ISSUE THREAD

**Issue by UnePierre** [onqtam/doctest#369]
My IDE (IAR EWARM) needs some weird tags (`"\x01<SRCREF file="..." line=... \x01>"`, `"\x01</SRCREF\x01>"`) around the file and line to produce a clickable link from console output.

I could write my own reporter, which would be a clone of the console reporter (which is fine!), just to add these tags into the output stream in `file_line_to_stream()` --- or this interface could be virtual and possible to override in a derived reporter implementation.

Overriding the remainder, DOCTEST_INTERNAL_ERROR, to produce a clickable link is rather easy, and superfluous.  Have I overlooked more ways in which doctest prints location information?

**Comment by onqtam** [comment]
Making `file_line_to_stream()` a member instead of a free function and also virtual seems like a good idea - it doesn't even need to be added to the base class API for reporters. I'll do that.

As for `DOCTEST_INTERNAL_ERROR` - would you like for me to add `#ifndef DOCTEST_INTERNAL_ERROR` & `#endif` around it so that you can more easily override it?

**Comment by UnePierre** [comment]
Thanks.

And: yes, please, also: thanks!

You're doing a very good job here!

**Comment by onqtam** [comment]
pushed in the dev branch

**Comment by UnePierre** [comment]
Works like a charm, at least for me.

BTW, here is the overriding for IAR EWARM, running doctest-enabled simulation in `cspybat` as a post-build action:
```
struct EWARM_Reporter : public doctest::ConsoleReporter
{
    EWARM_Reporter(const doctest::ContextOptions& in)
        : doctest::ConsoleReporter(in) { }

    virtual void file_line_to_stream(const char* file, int line, const char* tail = "") override
    {
        using namespace doctest;
        s << Color::LightGrey
          << "\x01<SRCREF file=\"" << file << "\" line=" << line << "\x01>"
          << skipPathFromFilename(file) << (opt.gnu_file_line ? ":" : "(")
          << (opt.no_line_numbers ? 0 : line) // 0 or the real num depending on the option
          << (opt.gnu_file_line ? ":" : "):")
          << "\x01</SRCREF\x01>"
          << tail;
    }
};

REGISTER_REPORTER("ewarm", 1, EWARM_Reporter); // "1" is the priority - used for ordering when multiple reporters/listeners are used
```
I might add some knowledge how to pass-in command-line arguments, and how to access the passed/failed status upon request.
