### ISSUE TITLE
Compile Error with CHECK_NOTHROW when using 2 Template Arguments

### ISSUE THREAD

**Issue by phil-zxx** [onqtam/doctest#372]
Let's consider the following sample script:

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

template<class A, class B>
struct TestClass
{
    TestClass(int v) : value(v) { }
    int value;
};

using TestClassIntFloat = TestClass<int, float>;

TEST_CASE("SomeUnitTest")
{
    CHECK(TestClass<int, float>(5).value == 5);
    // CHECK_NOTHROW(TestClass<int, float>(5));  // <-- Does not compile

    CHECK(TestClassIntFloat(5).value == 5);
    CHECK_NOTHROW(TestClassIntFloat(5));  // <-- Compiles just fine
}
```

Line `CHECK_NOTHROW(TestClass<int, float>(5));` does **not** compile. However, if I simply wrap the type via `using TestClassIntFloat = TestClass<int, float>;` then `CHECK_NOTHROW(TestClassIntFloat(5));` compiles just fine. Same issue for `CHECK_THROWS`.

I am using doctest `2.3.7` and the error occurs on both MSVC 2019 and g++ 10:

 - MSVC: `warning C4002: too many arguments for function-like macro invocation 'DOCTEST_CHECK_THROWS'`
- g++: `error: macro "DOCTEST_CHECK_THROWS" passed 2 arguments, but takes just 1`

---

This came up as I was trying to migrate from `catch2` to `doctest`. When reverting back to catch by using these two lines
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```
everything compiles, as expected.

---

I had a look at the code and i think changing this line
```cpp
#define CHECK_THROWS DOCTEST_CHECK_THROWS
```
to
```cpp
#define CHECK_THROWS(...) DOCTEST_CHECK_THROWS((__VA_ARGS__))
```
resolves the issue. But I am not sure if this has any other repercussions?

**Comment by onqtam** [comment]
fixed in the dev branch!

**Comment by phil-zxx** [comment]
Great, thanks a lot!
