### ISSUE TITLE
Scenario name can not be passed to -tc to execute single scenario

### ISSUE THREAD

**Issue by Mashewnutz** [onqtam/doctest#373]
## Description
Given the way the SCENARIO test macro works, it's not possible to use just the scenario name
as the command line argument with -tc= option to execute it.

### Steps to reproduce
Given this test case:

SCENARIO("MyTestCase")
...

Attempt to execture a single scenario using the command line filter:
-tc=MyTestCase

Result:
0 tests pass

### Extra information
It seems the SCENARIO macro prefixes the test case with '    Scenario:    ' (including whitespace).
So the filter requried to execute is:
-tc=*Scenario:*MyTestCase

Perhaps a new command argument could be used?

**Comment by onqtam** [comment]
I would lean towards people hacking their way around such issues because there's a fine balance between [features and bloat](https://github.com/onqtam/doctest/issues/374).

**Comment by Mashewnutz** [comment]
Sure, *Scenario:*MyTestCase gives the same result too, with just as many characters. My point was it’s  a bit unintuitive that’s all. 
The ‘Scenario:’ bit is kinda hidden without digging into the macro

**Comment by Mashewnutz** [comment]
I’m wondering why scenario test cases are prefixed with Scenario: at all, without this, they would work just fine with the standard filter.

**Comment by onqtam** [comment]
I think it was done the same way in Catch when I made it initially. Perhaps I should add a note about that in the docs - will keep this issue open for that.

**Comment by Mashewnutz** [comment]
Thanks, adding to the docs a note about this would be good too.

**Comment by onqtam** [comment]
added a note in the docs
