### ISSUE TITLE
Avoiding Feature Bloat

### ISSUE THREAD

**Issue by dwwork** [onqtam/doctest#374]
Following this discussion about Catch2 on [reddit](https://www.reddit.com/r/cpp/comments/gjp548/catch2_v300_preview2_catch2_now_uses_statically/?utm_source=share&utm_medium=web2x). Many people recommend this project as a replacement, mainly to get better compile times and the convenience of a header-only library.

The major complaint with Catch2 is that it got too big, too many features, too much complexity, which is what led to the excessive compile-times in the first place. 

I watched your CppCon 2017 presentation, and was impressed. However, I can't help but wonder, what is to keep this project from falling into the same trap? I ask because I'm looking for a unittesting framework for my very large project at work. In order to encourage adoption I want something that has simplicity as its guiding principle, as your project seems to.

**Comment by onqtam** [comment]
doctest will remain as light, transparent, and easy to use as possible - that's the only reason it exists in the first place. The current API will remain stable and any feature request is evaluated based on the design goals: https://github.com/onqtam/doctest/blob/master/doc/markdown/features.md

This means sometimes saying no to ideas - or at least finding a way to hack around it for a specific use case.
