### ISSUE TITLE
Feature Request: format PRIVATE/PUBLIC/INTERFACE entries with constant indentation

### ISSUE THREAD

**Issue by RedDwarf69** [onqtam/doctest#378]
I have been formatting my PRIVATE/PUBLIC/INTERFACE commands like this

```
target_link_libraries(
    targetA
    INTERFACE
        targetB
        targetC
    PUBLIC
        targetD
        targetE
)
```

I would not mind if it were
```
target_link_libraries(targetA
    INTERFACE
        targetB
        targetC
    PUBLIC
        targetD
        targetE
)
```

But I really like:
a) Always a single dependency by line
b) The constant indentation level of targetB and targetD, even if they are under specifiers (INTERFACE and PUBLIC) with different lengths.

After playing with the configuration file I have not seen any option to allow this. Would it be possible to make cmake-format format like this?

**Comment by onqtam** [comment]
Is it possible that this issue was directed at a different repository? :)

**Comment by RedDwarf69** [comment]
Ups -> https://github.com/cheshirekow/cmake_format/issues/206
