### ISSUE TITLE
How to understand "#data_array" in std::string?

### ISSUE THREAD

**Issue by beizhengren** [onqtam/doctest#383]
## Description

Hi, thanks for your terrific work.  
During I  add a test for vector, I find `#data_array`, as following.
I have never seen the programmer in c++. How should I understand it?
```
out.push_back(std::string(#data_array "[") + std::to_string(out.size() + 1) + "]"); \
```
the original link: https://github.com/onqtam/doctest/blob/master/doc/markdown/parameterized-tests.md
Thanks!

**Comment by onqtam** [comment]
Hi @beizhengren , If I understand you correctly, you are wondering what `#data_array` does exactly - that's a preprocessor operator and it makes whatever is passed to the macro as a C string literal. So for example:
```c++
    int data;
    std::list<int> my_real_data_array = {1, 2, 3, 4};
    DOCTEST_VALUE_PARAMETERIZED_DATA(data, my_real_data_array);
```
in this case there will be 4 subcases generated and each of them will be named `my_real_data_array[<index>]`.

Have a look at these links:
- https://stackoverflow.com/questions/10507264/how-to-use-macro-argument-as-string-literal
- https://en.cppreference.com/w/cpp/preprocessor/replace#.23_and_.23.23_operators
- https://gcc.gnu.org/onlinedocs/gcc-8.4.0/cpp/Stringizing.html

Let me know if this helps :)

**Comment by beizhengren** [comment]
Hi @onqtam 
Thank you so much for  your quick and clear reply!
It's my first time to know replacing text macros.
It help me a a lot！^ ^
