### ISSUE TITLE
Junit classname

### ISSUE THREAD

**Issue by dfleury2** [onqtam/doctest#390]
Hi,
I am using the last doctest 2.4.0 and the JUnit reporter. This is used only for Jenkins and its JUnit plugin.
I was wondering if the classname should be adapted to C++.
At this time, classname is "Java oriented", and grouped by package/class which are dot separated.
For C++, the dot is .cpp, so I got a cpp Class in Jenkins that looks "strange".
Is there improvement possible ?
Regards,

**Comment by onqtam** [comment]
Sorry for the late reply. The `classname` attribute is currently just the filename (`my_file.cpp`) as you have observed, but I'm not sure how to improve that... I just did what Catch2 does (unless I've missed something).

- One option would be to prepend the test case names (`my_test_case.my_file.cpp`) and even subcases (`my_subcase.my_test_case.my_file.cpp`) but the names could also have dots in them, + that's what the `name` attribute is for.
- another option would be to make [a new decorator](https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#decorators) that is junit-specific, but I'm not really fond of that...

**Comment by dfleury2** [comment]
It's fine. Thanks for your time answering me. This is more a bonus than a feature or issue.
Your first option was my favorite choice and I have started a patch, but too much issues happened while implemented it (filename can be tricky). So I gave up.
Since I move on another feature for my project, doctest works well (and now natively supported by CLion). 👍

**Comment by onqtam** [comment]
Cool :)
I guess I'll be closing this.
