### ISSUE TITLE
tests/asserts summary lines are misaligned when counts exceed 999999

### ISSUE THREAD

**Issue by dankamongmen** [onqtam/doctest#402]
**I have a working patch for this, which I am about to submit as a PR from the dankamongmen/doctest fork**

## Description
When there are more than a million assertions or testcases, or failures/passes thereof, the output is not aligned, and looks less attractive than it seemingly could:

```
===============================================================================
[doctest] test cases:     36 |     36 passed |      0 failed |      1 skipped
[doctest] assertions: 8509223 | 8509223 passed |      0 failed |
[doctest] Status: SUCCESS!
```

### Steps to reproduce
Build a `doctest` program using a million assertions or more. You're welcome to run `notcurses-tester` from the [Notcurses](https://github.com/dankamongmen/notcurses) project, where I was running into this.

### Extra information
* doctest version: **2.4.0** as packaged for Debian (2.4.0+repack0-1)
* Operating System: **Debian Unstable (Linux 5.7.10nlb)**
* Compiler+version: **gcc version 10.2.0 (Debian 10.2.0-3)** (invoked as g++)

**Comment by onqtam** [comment]
merged in `dev` - will soon release an official version!
