### ISSUE TITLE
create extensions header for optional features requiring more std includes or newer C++ features

### ISSUE THREAD

**Issue by Trass3r** [onqtam/doctest#405]
As mentioned in https://github.com/onqtam/doctest/issues/121#issuecomment-388090275, https://github.com/onqtam/doctest/issues/321#issuecomment-566925092, https://github.com/onqtam/doctest/issues/319#issuecomment-566247618, https://github.com/onqtam/doctest/issues/192#issuecomment-471519301, https://github.com/onqtam/doctest/issues/248#issuecomment-505161791.

**Comment by Trass3r** [comment]
E.g. stuff from https://github.com/onqtam/doctest/blob/master/examples/all_features/stringification.cpp

**Comment by onqtam** [comment]
@Trass3r Just wanted to let you know that I really appreciate the activity and will try to address most of it whenever I can, but August will be pretty busy...

**Comment by onqtam** [comment]
as mentioned [here](https://github.com/onqtam/doctest/issues/413) we'll be adding a new `doctest/extensions` folder where extension headers will be named `doctest_<whatever>.h` and there will be a single `extensions.md` file with documentation for them for now (each header having it's own `h1` heading with the ability to being linked to).
