### ISSUE TITLE
Avoid old C-style casts

### ISSUE THREAD

**Issue by UnePierre** [onqtam/doctest#424]
My IAR C++ compiler (EWARM8.40) issues a remark on constructs such as `(void)0`:
> Remark[Pa137]: use of C-style cast [...] 

Of course, this can be silenced in a doctest-trampoline header, but so far, it is the only remark that needs this.
I'd like to point out this feature of doctest: it is really silent warning/remark-wise! :-)

Pull-request #425 should fix that.

**Comment by onqtam** [comment]
Closing this now that the PR has been merged.
