### ISSUE TITLE
Exception handlers cause warnings when exceptions are disabled

### ISSUE THREAD

**Issue by nikoladimitroff** [onqtam/doctest#44]
C++ exceptions in my opinion (and in the [opinion of others](http://softwareengineering.stackexchange.com/questions/113479/are-there-any-real-world-cases-for-c-without-exceptions)) are subpar and I usually have them turned off along with RTTI. However,
the presence of try/catch blocks in doctest causes warnings (at least on MSVC - C4530) which can't be suppressed (and I'm building with /W4 /WX so this breaks my build).

I simply deleted / commented out all usages of try/catch in the my copy of the library but it will be helpful to only use exceptions handling if the user's exceptions are enabled. This can be detected by checking for
- `__cpp_exceptions` on gcc
- `_HAS_EXCEPTIONS` on MSVC

**Comment by onqtam** [comment]
try the dev branch and let me know if everything works fine - also checkout [these docs](https://github.com/onqtam/doctest/blob/dev/doc/markdown/configuration.md#doctest_config_no_exceptions) in the dev branch

**Comment by nikoladimitroff** [comment]
@onqtam Works as expected!
