### ISSUE TITLE
 log contexts for failures in JUnit reporter

### ISSUE THREAD

**Issue by runave** [onqtam/doctest#441]
## Description
We are using doctest with JUnit reports in our pipeline and if something goes wrong, then sometimes it's helpful to see the contexts of the failure as well.  
I have extended `JUnitReporter` with `log_contexts` in my fork, based on the similar functionality of `ConsoleReporter` - please feel free to accept the pull request.  
example failure with contexts:
```xml
      <failure message="1 != 1" type="CHECK">
logging.cpp(0):
CHECK( vec[i] != (1 &lt;&lt; i) ) is NOT correct!
  values: CHECK( 1 != 1 )
  logged: current iteration of loop:
          i := 0

      </failure>
```

**Comment by onqtam** [comment]
Merged the PR - closing this issue and will release a new version of doctest hopefully in 1-2 weeks.
