### ISSUE TITLE
Surpress warnings from clang-tidy

### ISSUE THREAD

**Issue by hg-zt** [onqtam/doctest#459]
## Description
We are using latest version of doctest and clang-tidy-12, and every `TEST_CASE/TEST_SUITE_BEGIN` violates `cppcoreguidelines-avoid-non-const-global-variables` and every `CHECK` violates `hicpp-no-assembler` because of [line 365](https://github.com/onqtam/doctest/blob/master/doctest/doctest.h#L365). Could you add `// NOLINT( <specific-rule> ) ` after these lines?

## Extra info
![image](https://user-images.githubusercontent.com/44964100/104891284-b112a180-59ab-11eb-9700-d3fa0029e7cb.png)

**Comment by onqtam** [comment]
just pushed a fix in the `dev` branch - let me know if it works for you!

**Comment by hg-zt** [comment]
It's `hicpp-no-assembler` not `icpp-no-assembler` (see https://clang.llvm.org/extra/clang-tidy/checks/hicpp-no-assembler.html). After fixing this typo, the `dev` branch works for me now.

**Comment by onqtam** [comment]
whops... just pushed the fix in the `dev` branch.
