### ISSUE TITLE
std::uncaught_exceptions is only available if compiling for macOS 10.12 or above

### ISSUE THREAD

**Issue by SamWindell** [onqtam/doctest#466]
Using doctest version 2.4.5 I'm getting a compile error for saying that std::uncaught_exceptions is only available for macos 10.12 or above. I need to target older macos systems so in my cmake project I use:

`set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9" CACHE STRING "Minimum OS X deployment version" FORCE)`

This option adds an argument to each compilation unit specifying it should compile for 10.9 support. The code in doctest currently checks for if the compiler has the std::uncaught_exceptions feature, but not if the macos version supports it too. 

My current workaround is to just ignore std::uncaught_exceptions on apple since the deprecation warning is suppressed anyways. Here's the code for that:

```
#if defined(__cpp_lib_uncaught_exceptions) && __cpp_lib_uncaught_exceptions >= 201411L && !defined(__APPLE__)
        if(std::uncaught_exceptions() > 0) {
#else
        if(std::uncaught_exception()) {
#endif
```

**Comment by onqtam** [comment]
fixed in `dev`
