### ISSUE TITLE
INFO does not compile when used like a function call

### ISSUE THREAD

**Issue by TestingPlant** [onqtam/doctest#469]
## Description
When `INFO` is used in code such as
```cpp
if (condition)
	INFO("Information");
```
it will not compile. However, if you add braces on like
```cpp
if (condition) {
	INFO("Information");
}
```
it compiles.

`INFO()` should act like any other function call, where you can omit the braces when used in if statements and such.

### Steps to reproduce
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "./doctest/doctest/doctest.h"

TEST_CASE("") {
	if (true)
		INFO("Information");
}
```

### Extra information

* doctest version: **v2.4.5**
* Operating System: **Arch Linux**
* Compiler+version: **g++ 10.2.0**

**Comment by onqtam** [comment]
Just pushed a fix for this in `dev` - thanks for reporting! I managed to change the entire macro to consist of a single statement so now it can be used properly like what you have suggested.

However, I should note that this usage is actually not useful at all - whatever is logged in an `INFO()` call will only be available for asserts which fail in it's block scope - and that block scope in this case is only the `then` part of the `if` statement - and thus you'd have no way of actually using whatever is logged in this way.
