### ISSUE TITLE
Add the include file to releases

### ISSUE THREAD

**Issue by agauniyal** [onqtam/doctest#47]
Would you mind adding the single header include file to [releases](https://github.com/onqtam/doctest/releases), which can easily be done by uploading via Github online release page. This will make it very easy to integrate with some other build systems and would save some time on low-speed connections too. I know we can download/clone the whole source anyways, but it would be much helpful if a direct download link to main file is provided :)

Thankyou

**Comment by onqtam** [comment]
I just added in the description of each release the following text:

    download the header from here

where ```here``` is a link to the associated header version.

You can also download the latest version (master branch) from this link:
https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h

**Comment by agauniyal** [comment]
yes absolutely 👍
