### ISSUE TITLE
Get list of registered test-case names

### ISSUE THREAD

**Issue by gamagan** [onqtam/doctest#479]
## Description
Please add a function to get a list of the registered test names.
I tried using this hack: https://github.com/onqtam/doctest/issues/184#issuecomment-464189323
but I get linker errors.

My usecase is that I'm creating tests for a GPU-accelerated 3D renderer. My testing setup requires that I run each test-case twice: 1 for setting up the frame data, and another to verify the rendered frame. This works fine.

I'm using `Context.addFilter("test-case", *testName)` to select the test to run. This works, but I have keep a manual list of test-names so that I can loop through them to run them. If I can get a list of test-case names from doctest, I don't have to keep the list manually updated: I can then just add new tests and they should run automatically.

## Extra information
* doctest version: 2.4.5
* Operating System: Windows 10
* Compiler+version:  MSVC 2019, v16.9

**Comment by onqtam** [comment]
I just pushed a fix for the linker error in the `dev` branch for that hack. At some point, there will be an official way but I can't guarantee a date for that.

**Comment by gamagan** [comment]
I just tried the new code and it does the trick for me. It's working well.

Thank you very much for making the updated, and also for doing it so quickly.
