### ISSUE TITLE
Dangling pointers with .str().c_str()

### ISSUE THREAD

**Issue by friendlyanon** [onqtam/doctest#494]
While working on #493, I noticed a [textbook example](https://en.cppreference.com/w/cpp/io/basic_ostringstream/str#Notes) of dangling pointer usage in doctest:

```
λ grep -nFe str().c_str() doctest\doctest.h
2973:        return oss.str().c_str();
2987:        return g_oss.str().c_str();
4163:            g_cs->stringifiedContexts.push_back(s.str().c_str());
5970:            DOCTEST_OUTPUT_DEBUG_STRING(oss.str().c_str());
```

**Comment by onqtam** [comment]
Hi, indeed there is a temporary object from which we get the `char*` pointer, but that pointer is not used after the statement - instead, it is either fed to a function that uses it immediately or it's passed to the constructor of a new `doctest::String` object which makes a full copy of the memory pointed to by the pointer. There are no dangling pointers.

**Comment by friendlyanon** [comment]
Hmm, you are right. The expression in these cases is not just the `.str().c_str()` chain, that's merely a sub-expression, even in the implicit conversion's case in the return statements.

I came to a conclusion a bit too eagerly it seems.
