### ISSUE TITLE
Dumping fixture state to disk on error

### ISSUE THREAD

**Issue by nextsilicon-itay-bookstein** [onqtam/doctest#509]
First of all, I want to second https://github.com/onqtam/doctest/issues/437 :)

I have tests from which I'd like to dump some state to disk on error, e.g. a before/after plot.
I was wonder whether there's a 'clean/correct' way to do this under doctest.
I thought about 'hooking' test errors through the listener interface, but I need to get at the test fixture's data to be able to introspect it and plot it to disk, and I didn't see a clean way to do this without passing through globals.

What do you think?
Thanks!

**Comment by onqtam** [comment]
Globals :)

**Comment by nextsilicon-itay-bookstein** [comment]
alrighty, thanks :)

**Comment by bilderbuchi** [comment]
The way I have used to trigger a dump lazily on error is to (ab)use an INFO message (which only trigger when a following assert fails):
```
INFO("Saving data to ", dump_data({actual, expected}));
CHECK(error < 0.02);
```
