### ISSUE TITLE
naming override in different testcase files

### ISSUE THREAD

**Issue by laoshaw** [onqtam/doctest#517]
## Description

I have two files happened to use the same class name(e.g. MyClass), doctest happily ignore the second MyClass and run all CHECK testcases again the first MyClass silently.

Can doctest.h issue an warning if it found overlapping filenames/classes from different testcase files instead of just ignoring the duplicate ones silently?

### Steps to reproduce

file1.cpp with class MyClass(){} with a few testcases.
file2.cpp with class MyClass(){} with a few different testcases.

doctest will run _all_ the testcases on one of the MyClass happily without warnings(assuming both set of testcases won't fail either  MyClass somehow)

### Extra information

* doctest version: **v2.4.6**
* Operating System: **ubuntu 20.04**
* Compiler+version: **g++-10**

**Comment by onqtam** [comment]
Having 2 different `MyClass` classes in 2 separate translation units is an ODR (one definition rule) violation which is a C++ problem and there's nothing doctest can do to detect such user errors - even the compiler tooling is bad at this last time I checked.
