### ISSUE TITLE
add <= and >= operators to Approx (and also maybe < and >)

### ISSUE THREAD

**Issue by onqtam** [onqtam/doctest#52]

**Comment by jonathansharman** [comment]
This seems unnecessary to me. The point of Approx is to compensate for the fact that floating-point imprecision leads to equality checks almost always being false. You shouldn't need to introduce an epsilon if you're testing for inequality.

**Comment by onqtam** [comment]
well the ```<=``` and ```>=``` operators got [added to Catch](https://github.com/philsquared/Catch/pull/715) so I figured I might as well do the same - it's just a few lines of code.

This is indeed not requested yet for doctest but someone might have a use for it - and it's trivial to implement. I'm wasting time with such minor stuff until I get back on the horse with big and important features.

Thanks for the interest!
