### ISSUE TITLE
CMAKE: doctest_discover_tests() error when ADD_LABELS is not specified

### ISSUE THREAD

**Issue by ArcEarth** [onqtam/doctest#524]
## Description
Regression introduced by https://github.com/onqtam/doctest/pull/464
When `doctest_discover_tests(<target>)` does not have `ADD_LABELS ...` options, test discovery breaks with the following error: 
```
[build] CMake Error at doctest/2.4.6/lib/cmake/doctestAddTests.cmake:60 (if):
[build]   if given arguments:
[build] 
[build]     "EQUAL" "1"
[build] 
[build]   Unknown arguments specified
```

### Steps to reproduce
Building anything with `doctest_discover_tests(<target>)` without extra options.

* doctest version: **v2.4.6**
* cmake version: **v3.19.4**
* Operating System: **OSX 11.4**
* Compiler+version: **Clang 11.0.4**

**Comment by jharmer95** [comment]
I have encountered this as well. Particularly annoying because I can't easily change the file for my CI/CD
Line 60 can be changed to either

`if (add_labels EQUAL 1)`

or

`if (${add_labels})`

I can prepare a PR for this fix

**Comment by onqtam** [comment]
should be fixed in `dev`!
