### ISSUE TITLE
FR: Documentation: FAQ: Add sectoin 'multiple files'

### ISSUE THREAD

**Issue by DarkTrick** [onqtam/doctest#526]
**Background**
I can't find a section on how to use use doctest with multiple test files. `include`ing the header in two files does apparently not work. 

**Feature Request**
Add a FAQ section `Compile with multiple files` (or similar), where `multiple files` would be a search keyword for simple browser search.

**Comment by danielytics** [comment]
> includeing the header in two files does apparently not work.

It works for me. I have a single source file containing
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest.h>
```
and then every source file that has tests just uses `#include <doctest.h>` on its own.

**Comment by onqtam** [comment]
fixed in `dev` - will publish a version soon
