### ISSUE TITLE
Faq googletest mocking dead link

### ISSUE THREAD

**Issue by araml** [onqtam/doctest#532]
The link to use integrate google mock with doctest in the [faq](https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#is-mocking-supported) is [dead](https://github.com/google/googletest/blob/master/googlemock/docs/ForDummies.md#using-google-mock-with-any-testing-framework)

There's an [issue]( https://github.com/google/googletest/issues/3280) on their repository that says that this isn't supported anymore and points out to a [link](https://chromium.googlesource.com/external/github.com/google/googletest/+/refs/tags/release-1.8.0/googlemock/docs/ForDummies.md#using-google-mock-with-any-testing-framework) to some old documentation (1.8 version and seems they're currently at at 1.11). 

I'm opening an issue because I don't know if you want to add the new link (to and old version of the doc) or just remove it since they're claiming to not support it/being tricky to integrate.

**Comment by onqtam** [comment]
I'll just outright remove it. Thanks!
