### ISSUE TITLE
VS 16.11 warning about unreferenced function with internal linkage

### ISSUE THREAD

**Issue by Reedbeta** [onqtam/doctest#533]
## Description

Compiling a fresh clone of doctest with Visual Studio 16.11 (using CMake generated projects, all default settings) gave me this warning:
```
C:\Source\doctest\doctest\parts\doctest.cpp(2132,57): error C2220: the following warning is treated as an error
C:\Source\doctest\doctest\parts\doctest.cpp(2132,57): warning C5245: 'doctest::`anonymous-namespace'::XmlWriter::ScopedElement::operator =': unreferenced function with internal linkage has been removed
C:\Source\doctest\doctest\parts\doctest.cpp(2132,57): message : to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
```
I was able to comment out the referenced `operator =` to get it compiling. Not sure if this is a new warning, but it might be a good candidate for disabling. It is one of the off-by-default warnings and seems closely related to C4514 "unreferenced inline function has been removed" which is already disabled in doctest.

### Extra information

* doctest version: **v2.4.6**
* Operating System: **Windows 10 20H2**
* Compiler+version: **Visual Studio 16.11.1 - cl.exe version 19.29.30133 for x64**

**Comment by onqtam** [comment]
this has been fixed in the `dev` branch in commit https://github.com/onqtam/doctest/commit/7baf9f4cfa6d5519315bc0e7d27ba802b59df5b7

**Comment by emmenlau** [comment]
Thanks!
