### ISSUE TITLE
-Wreserved-identifier warnings with Clang 13.0.0

### ISSUE THREAD

**Issue by nlohmann** [onqtam/doctest#536]
## Description

I want to compile my Doctest test suite with Clang 13.0.0 with maximal warnings. I use `-Weverything` with a few exceptions. Everything was fine with Clang 12.0.0, but with Clang 13.0.0, I get `-Wreserved-identifier` warnings:

```
/__w/json/json/test/thirdparty/doctest/doctest.h:2679:1: error: identifier '_DOCTEST_ANON_VAR_0' is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier]
DOCTEST_TEST_SUITE_END();
^
/__w/json/json/test/thirdparty/doctest/doctest.h:2009:32: note: expanded from macro 'DOCTEST_TEST_SUITE_END'
    DOCTEST_GLOBAL_NO_WARNINGS(DOCTEST_ANONYMOUS(_DOCTEST_ANON_VAR_)) =                            \
                               ^
/__w/json/json/test/thirdparty/doctest/doctest.h:330:30: note: expanded from macro 'DOCTEST_ANONYMOUS'
#define DOCTEST_ANONYMOUS(x) DOCTEST_CAT(x, __COUNTER__)
                             ^
/__w/json/json/test/thirdparty/doctest/doctest.h:328:29: note: expanded from macro 'DOCTEST_CAT'
#define DOCTEST_CAT(s1, s2) DOCTEST_CAT_IMPL(s1, s2)
                            ^
/__w/json/json/test/thirdparty/doctest/doctest.h:327:34: note: expanded from macro 'DOCTEST_CAT_IMPL'
#define DOCTEST_CAT_IMPL(s1, s2) s1##s2
                                 ^
<scratch space>:80:1: note: expanded from here
_DOCTEST_ANON_VAR_0
^
```

### Steps to reproduce

Compile a file that includes `doctest.h` with Clang 13.0.0 with `-Wreserved-identifier`.

### Extra information

* doctest version: **v2.4.6**
* Operating System: **Ubuntu 20.04.2 LTS** Linux-5.8.0-1039-azure; Distributor ID:	Ubuntu; Description:	Ubuntu 20.04.2 LTS; Release:	20.04; Codename:	focal; Linux 123725e37792 5.8.0-1039-azure 42~20.04.1-Ubuntu SMP Thu Jul 15 14:11:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compiler+version: **Clang 13.0.0**, Ubuntu clang version 13.0.0-++20210828094952+9c49fee5e7ac-1~exp1~20210828075752.71; Target: x86_64-pc-linux-gnu; Thread model: posix; InstalledDir: /usr/bin

**Comment by jktjkt** [comment]
PR #510 looks like a fix.

**Comment by nlohmann** [comment]
Yes, indeed. Any idea when will this be merged?

**Comment by nlohmann** [comment]
Duplicate of #507.

**Comment by emmenlau** [comment]
We have the same, can not build with clang 13 anymore. Thanks for your consideration!

**Comment by onqtam** [comment]
fixed in `dev` - new release soon!

**Comment by emmenlau** [comment]
Awesome, thanks!
