### ISSUE TITLE
Fails to build in VS2013 because of constexpr

### ISSUE THREAD

**Issue by sakhnik** [onqtam/doctest#539]
## Description

A project failed to build in VS 2013 because of `constexpr`. Succeeded when I substituted with `const`.
Is there a way to parameterize the build with macros like `DOCTEST_NOEXCEPT`?

### Extra information

* doctest version: **v2.4.6**
* Operating System: **Windows 10**
* Compiler+version: **VS 2013**

**Comment by onqtam** [comment]
done in the `dev` branch - use `DOCTEST_CONSTEXPR` :)
