### ISSUE TITLE
Output summary explanation

### ISSUE THREAD

**Issue by mangodan2003** [onqtam/doctest#541]
In the below what exactly is the figure in the first column after assertions?

I had assumed it was the number of assertions in code and compiled into the test binary, and thus that it would be constant from one run to the next, but in our CI test job that keeps failing this is an apparently random number, it might be 671 one run, and the next 633, then 710, etc.  I'm just trying to get a clue as to what on earth might be going on.

```
2021-10-05 15:20:16 - INFO     - | 1: ===============================================================================
32812021-10-05 15:20:16 - INFO     - | 1: [doctest] test cases:    100 |     88 passed |     12 failed |      0 skipped
32822021-10-05 15:20:16 - INFO     - | 1: [doctest] assertions:    671 |    659 passed |     12 failed |
32832021-10-05 15:20:16 - INFO     - | 1: [doctest] Status: FAILURE!
32842021-10-05 15:20:16 - INFO     - | 1/1 Test #1: my_tests .................***Failed   67.52 sec
```

**Comment by onqtam** [comment]
It cannot be the number of assertions in the binary - it's the number of encountered assertions during the run of the tests. If a test case exits prematurely then all assertions after it will not have been encountered.

If this number varies between runs without any changes to your code then there is something non-deterministic about your tests.
