### ISSUE TITLE
is it possible to define dependency for CHECKs

### ISSUE THREAD

**Issue by laoshaw** [onqtam/doctest#545]
since there is no logical operation allowed inside CHECK, e.g. `CHECK(result == 0 && myfunc() == 1)`, how can I make sure I only check `myfunc()==` after `result == 0`? can  I define a dependency somehow(i.e. only CHECK(condY) after CHECK(condX) passes.

**Comment by onqtam** [comment]
You can simply wrap the entire expression in another set of parenthesis: `CHECK( (result == 0 && myfunc() == 1) )` - however then you won't get the actual value of `result` or `myfunc()` in the output if the expression fails so the best alternative would be to use if statements and local variables. I don't think anything to support this will be to doctest (to avoid feature creep & bloat) so I'll be closing this issue.
