### ISSUE TITLE
Xcode 11.3 is gone from macOS-latest (=macOS-11)

### ISSUE THREAD

**Issue by jsoref** [onqtam/doctest#547]
### Steps to reproduce

1. Create a PR or commit that triggers a build

#### Results
https://github.com/onqtam/doctest/runs/4114874846?check_suite_focus=true

> xcode-select: error: invalid developer directory '/Applications/Xcode_11.3.app'
Error: Process completed with exit code 1.

### Extra information

* doctest version: **dev** (7810b9e3d2faedb2dcf81834da2be8d3025c022a)
* Operating System: **macOS 11.6.1**
* Compiler+version: **XCode 11.3** (sorta, it's requested by CI, but not available)

https://github.com/actions/virtual-environments/issues/4060

**Comment by onqtam** [comment]
PR merged.
