### ISSUE TITLE
"C4834: discarding return value" with REQUIRE_THROWS

### ISSUE THREAD

**Issue by Artalus** [onqtam/doctest#549]
## Description
This test assertion:
```cpp
map<string,string> stdmap;
REQUIRE_THROWS(stdmap.at("a").empty());
```
works fine, but triggers warning in MSVC during build:
```
ClCompile:
  ...\CL.exe ... main.cpp
  main.cpp
main.cpp(48,2): warning C4834: discarding return value of function with 'nodiscard' attribute
```
If I am not doing anything wrong, then this might become an issue if some project treats `C4834` as error.

### Steps to reproduce
```c++
#include <map>
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

TEST_CASE("std::map at") {
	std::map<std::string, std::string> args;
	REQUIRE_THROWS(args.at("a").empty());
}
```

### Extra information
* doctest version: **v2.4.6**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 2019 v16.11.5**

**Comment by onqtam** [comment]
Actually, you don't need to call `.empty()` because `.at()` will throw `std::out_of_range` in this case which is exactly what you are testing for. I don't think the framework should silence warnings for not using a result that has been marked as `nodiscard`. Let me know if you disagree - closing this for now.

**Comment by Artalus** [comment]
I actually added `.empty()` to ensure that the result returned from `.at()` was used, but apparently went not far enough! :) Checked it once more, and to actually silence the warning I had to use `args.at("a").empty() == true`.

But based on your comment, I assume that in all three cases I am doing something wrong. What is the intended way to test throwing from `nodiscard` functions then?

**Comment by onqtam** [comment]
Actually in your case `args.at("a").empty() == true` is fine, and an alternative way to do it would be `args.at("a") == "doesnt_matter"`.

**Comment by yeputons** [comment]
Note that one can `#define DOCTEST_CONFIG_VOID_CAST_EXPRESSIONS` so all exception-handling macros (including `REQUIRE_THROWS`) wrap their argument in `static_cast<void>(....)` which suppresses this warning. It's not the default behavior to support `{ ... }` blocks inside the macro, see [docs](https://github.com/doctest/doctest/blob/7b9885133108ae301ddd16e2651320f54cafeba7/doc/markdown/configuration.md#doctest_config_void_cast_expressions).
