### ISSUE TITLE
Add ability to filter subcases with filters

### ISSUE THREAD

**Issue by onqtam** [onqtam/doctest#57]

**Comment by onqtam** [comment]
Given the following code:

```c++
TEST_CASE("Test") {
    cout << "root" << endl;
    SECTION( "sa" ) {
        cout << "sa" << endl;
        SECTION( "sb" ) {
            cout << "sb" << endl;
        }
        SECTION( "sc" ) {
            cout << "sc" << endl;
        }
    }
    SECTION( "sd" ) {
        cout << "sd" << endl;
    }
}
```

To execute only ```sa / sb``` run with ```--subcase=sa,*b```
To execute anything inside of ```sa``` run with ```--subcase=sa --subcase-filter-levels=1```

**Comment by iamviji** [comment]
How to select single subcase at the leaf level? Eg : I would like to run sa.sa.sb.sb

**Comment by iamviji** [comment]
how to execute only one leaf test case? for example  sb-level1/sb-level-2/sb-level3

**Comment by onqtam** [comment]
@iamviji in the example from this issue the following works to execute one specific leaf: `-sc=sa,sc`

**Comment by iamviji** [comment]
Thanks. I have tried that. 
    TEST_CASE("TC")
    {
        MESSAGE("TC");
        SUBCASE("SB1")
        {
            MESSAGE("TC.SB1");
            SUBCASE("SB1") { MESSAGE("TC.SB1.SB1"); }
            SUBCASE("SB2") { MESSAGE("TC.SB1.SB2"); }
        }
        SUBCASE("SB2")
        {
            MESSAGE("TC.SB2");
            SUBCASE("SB1") { MESSAGE("TC.SB2.SB1"); }
            SUBCASE("SB2") { MESSAGE("TC.SB2.SB2"); }
        }
    }
command tried:
-tc=TC -sc=SB1,SB2

output:
MESSAGE:TC
MESSAGE:TC.SB1
MESSAGE:TC.SB1.SB1
MESSAGE:TC
MESSAGE:TC.SB1
MESSAGE:TC.SB1.SB2
MESSAGE:TC
MESSAGE:TC.SB2
MESSAGE:TC.SB2.SB1
MESSAGE:TC
MESSAGE:TC.SB2
MESSAGE:TC.SB2.SB2

but I expect 
MESSAGE:TC
MESSAGE:TC.SB1
MESSAGE:TC.SB1.SB2

**Comment by onqtam** [comment]
@iamviji there are identical subcase names which are nested within each other. Try with different names like this:

```c++
    TEST_CASE("TC")
    {
        MESSAGE("TC");
        SUBCASE("SB1_root")
        {
            MESSAGE("TC.SB1_root");
            SUBCASE("SB1") { MESSAGE("TC.SB1_root.SB1"); }
            SUBCASE("SB2") { MESSAGE("TC.SB1_root.SB2"); }
        }
        SUBCASE("SB2_root")
        {
            MESSAGE("TC.SB2_root");
            SUBCASE("SB1") { MESSAGE("TC.SB2_root.SB1"); }
            SUBCASE("SB2") { MESSAGE("TC.SB2_root.SB2"); }
        }
    }
```

```-sc=SB1_ROOT,SB2```

**Comment by iamviji** [comment]
I see
