### ISSUE TITLE
No red when all tests pass

### ISSUE THREAD

**Issue by lichray** [onqtam/doctest#7]
A red "failed 0" looks very scary.  Please make the report more peaceful.

**Comment by onqtam** [comment]
Will do it in a few days for 1.1

**Comment by ferkulat** [comment]
I tried 362c8dd3dfa3e2cbef132cdf57aab6b08bd2a66c and if a test fails, I still see green color in the out put. To overview the results as quick as possible, I would prefer to see either green or red, but not both in the out put.

Thank you a lot for your work

with best regards

**Comment by onqtam** [comment]
@ferkulat I suppose you are not talking about the summary of the tests as the original OP - but about the output for each failed assert - and currently parts of the message are in green - maybe it was a bad choise... I might change it... but in the distant future colors might be configurable.
