### ISSUE TITLE
Static Analysis results of doctest

### ISSUE THREAD

**Issue by martinmoene** [onqtam/doctest#83]
[martinmoene/doctest Static Analyses](https://gist.github.com/martinmoene/e7ae98c580917064de927e16bbb00f0f).

Contains 

- [PVS-Studio](https://gist.github.com/martinmoene/e7ae98c580917064de927e16bbb00f0f#file-pvs-studio-txt)
- [Resharper-C++](https://gist.github.com/martinmoene/e7ae98c580917064de927e16bbb00f0f#file-resharperc-txt)
- [VC-CppCoreCheck-released.txt](https://gist.github.com/martinmoene/e7ae98c580917064de927e16bbb00f0f#file-vc-cppcorecheck-released-txt)

**Comment by onqtam** [comment]
Thanks for these!

Currently doctest is per-push statically analyzed with these: Cppcheck / Clang-Tidy / Coverity Scan / OCLint / Visual Studio Analyzer (as can be seen [here](https://github.com/onqtam/doctest/blob/1.2.1/.travis.yml#L398)) - but to be clean I pass quite a bunch of suppression flags though...

I'll look into the lists you supplied in a few weeks when I have more time - they are exactly the ones I'm not currently using.

**Comment by martinmoene** [comment]
You're welcome. 

I had not looked at [`.travis.yml`](https://github.com/onqtam/doctest/blob/1.2.1/.travis.yml#L398) in earnest, I'm easily intimidated when it's larger then 42 lines 😉 .

One on the most intriguing messages:
```
doctest.h:992 'short' type cannot be unsigned
```
I like the order `int short unsigned` as written.

**Comment by onqtam** [comment]
weird - I think short can be unsigned...
Anyway I've written it that way so I can easily glance over the overloads that are provided and check if something is missing - in any other context I would write it as ```unsigned short```

I'm going through the logs at the moment and fixing some things, but not all - many of them I would suppress.
