### ISSUE TITLE
Xcode 9 / clang - unknown warning group

### ISSUE THREAD

**Issue by Deadpikle** [onqtam/doctest#92]
## Description

When building some code that includes doctest, the following warning is emitted on line 65 of the combined header: 
```
Unknown warning group - '-Wzero-as-null-pointer-constant', ignored
```

### Steps to reproduce

To reproduce, simply attempt to build the some code that uses doctest.

### Suggested Fix (adjusted from similar error [here](https://github.com/nicklockwood/iCarousel/pull/744))

```
#if !defined(__has_warning) || __has_warning("-Wzero-as-null-pointer-constant")
# pragma GCC diagnostic ignored "-Wzero-as-null-pointer-constant"
#endif
```

### Extra information

* doctest version: **v1.2.1**
* Operating System: **macOS Sierra**
* Compiler+version: **Xcode 9 / Clang 9 (I think it's clang 9?)**

re: clang version: 
```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by onqtam** [comment]
Should be fixed - [this build](https://travis-ci.org/onqtam/doctest/jobs/284087075) passed :)
